//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChallengeSpec) DeepCopyInto(out *ChallengeSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChallengeSpec.
func (in *ChallengeSpec) DeepCopy() *ChallengeSpec {
	if in == nil {
		return nil
	}
	out := new(ChallengeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointResultStatus) DeepCopyInto(out *CheckpointResultStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointResultStatus.
func (in *CheckpointResultStatus) DeepCopy() *CheckpointResultStatus {
	if in == nil {
		return nil
	}
	out := new(CheckpointResultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointStatus) DeepCopyInto(out *CheckpointStatus) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]CheckpointResultStatus, len(*in))
		copy(*out, *in)
	}
	if in.CheckedAt != nil {
		in, out := &in.CheckedAt, &out.CheckedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointStatus.
func (in *CheckpointStatus) DeepCopy() *CheckpointStatus {
	if in == nil {
		return nil
	}
	out := new(CheckpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanupPolicySpec) DeepCopyInto(out *CleanupPolicySpec) {
	*out = *in
	if in.AutoDestroyAfterIdle != nil {
		in, out := &in.AutoDestroyAfterIdle, &out.AutoDestroyAfterIdle
		*out = new(bool)
		**out = **in
	}
	if in.ForceCleanupOnFailure != nil {
		in, out := &in.ForceCleanupOnFailure, &out.ForceCleanupOnFailure
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanupPolicySpec.
func (in *CleanupPolicySpec) DeepCopy() *CleanupPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CleanupPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonEnvironmentSpec) DeepCopyInto(out *CommonEnvironmentSpec) {
	*out = *in
	if in.CheckpointIDs != nil {
		in, out := &in.CheckpointIDs, &out.CheckpointIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ActivityAt != nil {
		in, out := &in.ActivityAt, &out.ActivityAt
		*out = (*in).DeepCopy()
	}
	in.Timeouts.DeepCopyInto(&out.Timeouts)
	in.CleanupPolicy.DeepCopyInto(&out.CleanupPolicy)
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonEnvironmentSpec.
func (in *CommonEnvironmentSpec) DeepCopy() *CommonEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(CommonEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonEnvironmentStatus) DeepCopyInto(out *CommonEnvironmentStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.ReadyAt != nil {
		in, out := &in.ReadyAt, &out.ReadyAt
		*out = (*in).DeepCopy()
	}
	if in.LastActivityAt != nil {
		in, out := &in.LastActivityAt, &out.LastActivityAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.DestroyedAt != nil {
		in, out := &in.DestroyedAt, &out.DestroyedAt
		*out = (*in).DeepCopy()
	}
	if in.LastError != nil {
		in, out := &in.LastError, &out.LastError
		*out = new(EnvironmentErrorStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Checkpoints != nil {
		in, out := &in.Checkpoints, &out.Checkpoints
		*out = new(CheckpointStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonEnvironmentStatus.
func (in *CommonEnvironmentStatus) DeepCopy() *CommonEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(CommonEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerEnvironment) DeepCopyInto(out *ContainerEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerEnvironment.
func (in *ContainerEnvironment) DeepCopy() *ContainerEnvironment {
	if in == nil {
		return nil
	}
	out := new(ContainerEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerEnvironmentList) DeepCopyInto(out *ContainerEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerEnvironmentList.
func (in *ContainerEnvironmentList) DeepCopy() *ContainerEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(ContainerEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentErrorStatus) DeepCopyInto(out *EnvironmentErrorStatus) {
	*out = *in
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentErrorStatus.
func (in *EnvironmentErrorStatus) DeepCopy() *EnvironmentErrorStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentErrorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentResourcesSpec) DeepCopyInto(out *EnvironmentResourcesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentResourcesSpec.
func (in *EnvironmentResourcesSpec) DeepCopy() *EnvironmentResourcesSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentResourcesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentTimeoutsSpec) DeepCopyInto(out *EnvironmentTimeoutsSpec) {
	*out = *in
	if in.ReadyTimeoutSeconds != nil {
		in, out := &in.ReadyTimeoutSeconds, &out.ReadyTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	if in.IdleTTLSeconds != nil {
		in, out := &in.IdleTTLSeconds, &out.IdleTTLSeconds
		*out = new(int64)
		**out = **in
	}
	if in.DrainGracePeriodSeconds != nil {
		in, out := &in.DrainGracePeriodSeconds, &out.DrainGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.DestroyTimeoutSeconds != nil {
		in, out := &in.DestroyTimeoutSeconds, &out.DestroyTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentTimeoutsSpec.
func (in *EnvironmentTimeoutsSpec) DeepCopy() *EnvironmentTimeoutsSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentTimeoutsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Generation) DeepCopyInto(out *Generation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Generation.
func (in *Generation) DeepCopy() *Generation {
	if in == nil {
		return nil
	}
	out := new(Generation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Generation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenerationList) DeepCopyInto(out *GenerationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Generation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenerationList.
func (in *GenerationList) DeepCopy() *GenerationList {
	if in == nil {
		return nil
	}
	out := new(GenerationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenerationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenerationSpec) DeepCopyInto(out *GenerationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenerationSpec.
func (in *GenerationSpec) DeepCopy() *GenerationSpec {
	if in == nil {
		return nil
	}
	out := new(GenerationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenerationStatus) DeepCopyInto(out *GenerationStatus) {
	*out = *in
	if in.Challenge != nil {
		in, out := &in.Challenge, &out.Challenge
		*out = new(ChallengeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenerationStatus.
func (in *GenerationStatus) DeepCopy() *GenerationStatus {
	if in == nil {
		return nil
	}
	out := new(GenerationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterEnvironment) DeepCopyInto(out *VClusterEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterEnvironment.
func (in *VClusterEnvironment) DeepCopy() *VClusterEnvironment {
	if in == nil {
		return nil
	}
	out := new(VClusterEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VClusterEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterEnvironmentList) DeepCopyInto(out *VClusterEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VClusterEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterEnvironmentList.
func (in *VClusterEnvironmentList) DeepCopy() *VClusterEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(VClusterEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VClusterEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterEnvironmentSpec) DeepCopyInto(out *VClusterEnvironmentSpec) {
	*out = *in
	in.CommonEnvironmentSpec.DeepCopyInto(&out.CommonEnvironmentSpec)
	out.VCluster = in.VCluster
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterEnvironmentSpec.
func (in *VClusterEnvironmentSpec) DeepCopy() *VClusterEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(VClusterEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterEnvironmentStatus) DeepCopyInto(out *VClusterEnvironmentStatus) {
	*out = *in
	in.CommonEnvironmentStatus.DeepCopyInto(&out.CommonEnvironmentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterEnvironmentStatus.
func (in *VClusterEnvironmentStatus) DeepCopy() *VClusterEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(VClusterEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterRuntimeSpec) DeepCopyInto(out *VClusterRuntimeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterRuntimeSpec.
func (in *VClusterRuntimeSpec) DeepCopy() *VClusterRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(VClusterRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyIssue) DeepCopyInto(out *VerifyIssue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyIssue.
func (in *VerifyIssue) DeepCopy() *VerifyIssue {
	if in == nil {
		return nil
	}
	out := new(VerifyIssue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyReport) DeepCopyInto(out *VerifyReport) {
	*out = *in
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = make([]VerifyIssue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyReport.
func (in *VerifyReport) DeepCopy() *VerifyReport {
	if in == nil {
		return nil
	}
	out := new(VerifyReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyTask) DeepCopyInto(out *VerifyTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyTask.
func (in *VerifyTask) DeepCopy() *VerifyTask {
	if in == nil {
		return nil
	}
	out := new(VerifyTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerifyTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyTaskList) DeepCopyInto(out *VerifyTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VerifyTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyTaskList.
func (in *VerifyTaskList) DeepCopy() *VerifyTaskList {
	if in == nil {
		return nil
	}
	out := new(VerifyTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerifyTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyTaskSource) DeepCopyInto(out *VerifyTaskSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyTaskSource.
func (in *VerifyTaskSource) DeepCopy() *VerifyTaskSource {
	if in == nil {
		return nil
	}
	out := new(VerifyTaskSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyTaskSpec) DeepCopyInto(out *VerifyTaskSpec) {
	*out = *in
	out.Source = in.Source
	out.Submission = in.Submission
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyTaskSpec.
func (in *VerifyTaskSpec) DeepCopy() *VerifyTaskSpec {
	if in == nil {
		return nil
	}
	out := new(VerifyTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyTaskStatus) DeepCopyInto(out *VerifyTaskStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Report != nil {
		in, out := &in.Report, &out.Report
		*out = new(VerifyReport)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyTaskStatus.
func (in *VerifyTaskStatus) DeepCopy() *VerifyTaskStatus {
	if in == nil {
		return nil
	}
	out := new(VerifyTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyTaskSubmission) DeepCopyInto(out *VerifyTaskSubmission) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyTaskSubmission.
func (in *VerifyTaskSubmission) DeepCopy() *VerifyTaskSubmission {
	if in == nil {
		return nil
	}
	out := new(VerifyTaskSubmission)
	in.DeepCopyInto(out)
	return out
}
