//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointResultStatus) DeepCopyInto(out *CheckpointResultStatus) {
	*out = *in
	if in.FirstPassedAt != nil {
		in, out := &in.FirstPassedAt, &out.FirstPassedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointResultStatus.
func (in *CheckpointResultStatus) DeepCopy() *CheckpointResultStatus {
	if in == nil {
		return nil
	}
	out := new(CheckpointResultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointStatus) DeepCopyInto(out *CheckpointStatus) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]CheckpointResultStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CheckedAt != nil {
		in, out := &in.CheckedAt, &out.CheckedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointStatus.
func (in *CheckpointStatus) DeepCopy() *CheckpointStatus {
	if in == nil {
		return nil
	}
	out := new(CheckpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanupPolicySpec) DeepCopyInto(out *CleanupPolicySpec) {
	*out = *in
	if in.AutoDestroyAfterIdle != nil {
		in, out := &in.AutoDestroyAfterIdle, &out.AutoDestroyAfterIdle
		*out = new(bool)
		**out = **in
	}
	if in.ForceCleanupOnFailure != nil {
		in, out := &in.ForceCleanupOnFailure, &out.ForceCleanupOnFailure
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanupPolicySpec.
func (in *CleanupPolicySpec) DeepCopy() *CleanupPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CleanupPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonEnvironmentSpec) DeepCopyInto(out *CommonEnvironmentSpec) {
	*out = *in
	if in.CheckpointIDs != nil {
		in, out := &in.CheckpointIDs, &out.CheckpointIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ActivityAt != nil {
		in, out := &in.ActivityAt, &out.ActivityAt
		*out = (*in).DeepCopy()
	}
	in.Timeouts.DeepCopyInto(&out.Timeouts)
	in.CleanupPolicy.DeepCopyInto(&out.CleanupPolicy)
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonEnvironmentSpec.
func (in *CommonEnvironmentSpec) DeepCopy() *CommonEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(CommonEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonEnvironmentStatus) DeepCopyInto(out *CommonEnvironmentStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.ReadyAt != nil {
		in, out := &in.ReadyAt, &out.ReadyAt
		*out = (*in).DeepCopy()
	}
	if in.LastActivityAt != nil {
		in, out := &in.LastActivityAt, &out.LastActivityAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.DestroyedAt != nil {
		in, out := &in.DestroyedAt, &out.DestroyedAt
		*out = (*in).DeepCopy()
	}
	if in.LastError != nil {
		in, out := &in.LastError, &out.LastError
		*out = new(EnvironmentErrorStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Checkpoints != nil {
		in, out := &in.Checkpoints, &out.Checkpoints
		*out = new(CheckpointStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonEnvironmentStatus.
func (in *CommonEnvironmentStatus) DeepCopy() *CommonEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(CommonEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerEnvironment) DeepCopyInto(out *ContainerEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerEnvironment.
func (in *ContainerEnvironment) DeepCopy() *ContainerEnvironment {
	if in == nil {
		return nil
	}
	out := new(ContainerEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerEnvironmentList) DeepCopyInto(out *ContainerEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerEnvironmentList.
func (in *ContainerEnvironmentList) DeepCopy() *ContainerEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(ContainerEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentCheckpointSpec) DeepCopyInto(out *EnvironmentCheckpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentCheckpointSpec.
func (in *EnvironmentCheckpointSpec) DeepCopy() *EnvironmentCheckpointSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentCheckpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentErrorStatus) DeepCopyInto(out *EnvironmentErrorStatus) {
	*out = *in
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentErrorStatus.
func (in *EnvironmentErrorStatus) DeepCopy() *EnvironmentErrorStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentErrorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentFailureStatus) DeepCopyInto(out *EnvironmentFailureStatus) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentFailureStatus.
func (in *EnvironmentFailureStatus) DeepCopy() *EnvironmentFailureStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentFailureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentLifecycleSpec) DeepCopyInto(out *EnvironmentLifecycleSpec) {
	*out = *in
	if in.ActivityAt != nil {
		in, out := &in.ActivityAt, &out.ActivityAt
		*out = (*in).DeepCopy()
	}
	if in.DeadlineAt != nil {
		in, out := &in.DeadlineAt, &out.DeadlineAt
		*out = (*in).DeepCopy()
	}
	if in.IdleTTLSeconds != nil {
		in, out := &in.IdleTTLSeconds, &out.IdleTTLSeconds
		*out = new(int64)
		**out = **in
	}
	if in.DrainGracePeriodSeconds != nil {
		in, out := &in.DrainGracePeriodSeconds, &out.DrainGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentLifecycleSpec.
func (in *EnvironmentLifecycleSpec) DeepCopy() *EnvironmentLifecycleSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentLifecycleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentResourcesSpec) DeepCopyInto(out *EnvironmentResourcesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentResourcesSpec.
func (in *EnvironmentResourcesSpec) DeepCopy() *EnvironmentResourcesSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentResourcesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentSourceSpec) DeepCopyInto(out *EnvironmentSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentSourceSpec.
func (in *EnvironmentSourceSpec) DeepCopy() *EnvironmentSourceSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentSpec) DeepCopyInto(out *EnvironmentSpec) {
	*out = *in
	out.Source = in.Source
	if in.Checkpoints != nil {
		in, out := &in.Checkpoints, &out.Checkpoints
		*out = make([]EnvironmentCheckpointSpec, len(*in))
		copy(*out, *in)
	}
	in.Lifecycle.DeepCopyInto(&out.Lifecycle)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentSpec.
func (in *EnvironmentSpec) DeepCopy() *EnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentStatus) DeepCopyInto(out *EnvironmentStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.ReadyAt != nil {
		in, out := &in.ReadyAt, &out.ReadyAt
		*out = (*in).DeepCopy()
	}
	if in.LastActivityAt != nil {
		in, out := &in.LastActivityAt, &out.LastActivityAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.DestroyedAt != nil {
		in, out := &in.DestroyedAt, &out.DestroyedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Failure != nil {
		in, out := &in.Failure, &out.Failure
		*out = new(EnvironmentFailureStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Checkpoints != nil {
		in, out := &in.Checkpoints, &out.Checkpoints
		*out = new(CheckpointStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentStatus.
func (in *EnvironmentStatus) DeepCopy() *EnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentTimeoutsSpec) DeepCopyInto(out *EnvironmentTimeoutsSpec) {
	*out = *in
	if in.ReadyTimeoutSeconds != nil {
		in, out := &in.ReadyTimeoutSeconds, &out.ReadyTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	if in.IdleTTLSeconds != nil {
		in, out := &in.IdleTTLSeconds, &out.IdleTTLSeconds
		*out = new(int64)
		**out = **in
	}
	if in.DrainGracePeriodSeconds != nil {
		in, out := &in.DrainGracePeriodSeconds, &out.DrainGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.DestroyTimeoutSeconds != nil {
		in, out := &in.DestroyTimeoutSeconds, &out.DestroyTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentTimeoutsSpec.
func (in *EnvironmentTimeoutsSpec) DeepCopy() *EnvironmentTimeoutsSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentTimeoutsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeEnvironment) DeepCopyInto(out *NodeEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeEnvironment.
func (in *NodeEnvironment) DeepCopy() *NodeEnvironment {
	if in == nil {
		return nil
	}
	out := new(NodeEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeEnvironmentList) DeepCopyInto(out *NodeEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeEnvironmentList.
func (in *NodeEnvironmentList) DeepCopy() *NodeEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(NodeEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeEnvironmentSpec) DeepCopyInto(out *NodeEnvironmentSpec) {
	*out = *in
	in.Environment.DeepCopyInto(&out.Environment)
	in.Runtime.DeepCopyInto(&out.Runtime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeEnvironmentSpec.
func (in *NodeEnvironmentSpec) DeepCopy() *NodeEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(NodeEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeEnvironmentStatus) DeepCopyInto(out *NodeEnvironmentStatus) {
	*out = *in
	in.Environment.DeepCopyInto(&out.Environment)
	in.Runtime.DeepCopyInto(&out.Runtime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeEnvironmentStatus.
func (in *NodeEnvironmentStatus) DeepCopy() *NodeEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(NodeEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInstanceStatus) DeepCopyInto(out *NodeInstanceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInstanceStatus.
func (in *NodeInstanceStatus) DeepCopy() *NodeInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(NodeInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceSnapshot) DeepCopyInto(out *NodeResourceSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceSnapshot.
func (in *NodeResourceSnapshot) DeepCopy() *NodeResourceSnapshot {
	if in == nil {
		return nil
	}
	out := new(NodeResourceSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRuntimeNodeSpec) DeepCopyInto(out *NodeRuntimeNodeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRuntimeNodeSpec.
func (in *NodeRuntimeNodeSpec) DeepCopy() *NodeRuntimeNodeSpec {
	if in == nil {
		return nil
	}
	out := new(NodeRuntimeNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRuntimeSnapshot) DeepCopyInto(out *NodeRuntimeSnapshot) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeRuntimeNodeSpec, len(*in))
		copy(*out, *in)
	}
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRuntimeSnapshot.
func (in *NodeRuntimeSnapshot) DeepCopy() *NodeRuntimeSnapshot {
	if in == nil {
		return nil
	}
	out := new(NodeRuntimeSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRuntimeStatus) DeepCopyInto(out *NodeRuntimeStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeInstanceStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRuntimeStatus.
func (in *NodeRuntimeStatus) DeepCopy() *NodeRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterEnvironment) DeepCopyInto(out *VClusterEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterEnvironment.
func (in *VClusterEnvironment) DeepCopy() *VClusterEnvironment {
	if in == nil {
		return nil
	}
	out := new(VClusterEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VClusterEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterEnvironmentList) DeepCopyInto(out *VClusterEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VClusterEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterEnvironmentList.
func (in *VClusterEnvironmentList) DeepCopy() *VClusterEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(VClusterEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VClusterEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterEnvironmentSpec) DeepCopyInto(out *VClusterEnvironmentSpec) {
	*out = *in
	in.CommonEnvironmentSpec.DeepCopyInto(&out.CommonEnvironmentSpec)
	out.VCluster = in.VCluster
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterEnvironmentSpec.
func (in *VClusterEnvironmentSpec) DeepCopy() *VClusterEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(VClusterEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterEnvironmentStatus) DeepCopyInto(out *VClusterEnvironmentStatus) {
	*out = *in
	in.CommonEnvironmentStatus.DeepCopyInto(&out.CommonEnvironmentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterEnvironmentStatus.
func (in *VClusterEnvironmentStatus) DeepCopy() *VClusterEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(VClusterEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterRuntimeSpec) DeepCopyInto(out *VClusterRuntimeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterRuntimeSpec.
func (in *VClusterRuntimeSpec) DeepCopy() *VClusterRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(VClusterRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sEnvironment) DeepCopyInto(out *VK8sEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sEnvironment.
func (in *VK8sEnvironment) DeepCopy() *VK8sEnvironment {
	if in == nil {
		return nil
	}
	out := new(VK8sEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VK8sEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sEnvironmentList) DeepCopyInto(out *VK8sEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VK8sEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sEnvironmentList.
func (in *VK8sEnvironmentList) DeepCopy() *VK8sEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(VK8sEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VK8sEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sEnvironmentSpec) DeepCopyInto(out *VK8sEnvironmentSpec) {
	*out = *in
	in.Environment.DeepCopyInto(&out.Environment)
	out.Runtime = in.Runtime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sEnvironmentSpec.
func (in *VK8sEnvironmentSpec) DeepCopy() *VK8sEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(VK8sEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sEnvironmentStatus) DeepCopyInto(out *VK8sEnvironmentStatus) {
	*out = *in
	in.Environment.DeepCopyInto(&out.Environment)
	out.Runtime = in.Runtime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sEnvironmentStatus.
func (in *VK8sEnvironmentStatus) DeepCopy() *VK8sEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(VK8sEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sResourceSnapshot) DeepCopyInto(out *VK8sResourceSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sResourceSnapshot.
func (in *VK8sResourceSnapshot) DeepCopy() *VK8sResourceSnapshot {
	if in == nil {
		return nil
	}
	out := new(VK8sResourceSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sRuntimeSnapshot) DeepCopyInto(out *VK8sRuntimeSnapshot) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sRuntimeSnapshot.
func (in *VK8sRuntimeSnapshot) DeepCopy() *VK8sRuntimeSnapshot {
	if in == nil {
		return nil
	}
	out := new(VK8sRuntimeSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sRuntimeStatus) DeepCopyInto(out *VK8sRuntimeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sRuntimeStatus.
func (in *VK8sRuntimeStatus) DeepCopy() *VK8sRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(VK8sRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyIssue) DeepCopyInto(out *VerifyIssue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyIssue.
func (in *VerifyIssue) DeepCopy() *VerifyIssue {
	if in == nil {
		return nil
	}
	out := new(VerifyIssue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyReport) DeepCopyInto(out *VerifyReport) {
	*out = *in
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = make([]VerifyIssue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyReport.
func (in *VerifyReport) DeepCopy() *VerifyReport {
	if in == nil {
		return nil
	}
	out := new(VerifyReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyTask) DeepCopyInto(out *VerifyTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyTask.
func (in *VerifyTask) DeepCopy() *VerifyTask {
	if in == nil {
		return nil
	}
	out := new(VerifyTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerifyTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyTaskExecution) DeepCopyInto(out *VerifyTaskExecution) {
	*out = *in
	if in.CheckpointIDs != nil {
		in, out := &in.CheckpointIDs, &out.CheckpointIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyTaskExecution.
func (in *VerifyTaskExecution) DeepCopy() *VerifyTaskExecution {
	if in == nil {
		return nil
	}
	out := new(VerifyTaskExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyTaskList) DeepCopyInto(out *VerifyTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VerifyTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyTaskList.
func (in *VerifyTaskList) DeepCopy() *VerifyTaskList {
	if in == nil {
		return nil
	}
	out := new(VerifyTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerifyTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyTaskSource) DeepCopyInto(out *VerifyTaskSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyTaskSource.
func (in *VerifyTaskSource) DeepCopy() *VerifyTaskSource {
	if in == nil {
		return nil
	}
	out := new(VerifyTaskSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyTaskSpec) DeepCopyInto(out *VerifyTaskSpec) {
	*out = *in
	out.Source = in.Source
	out.Submission = in.Submission
	in.Execution.DeepCopyInto(&out.Execution)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyTaskSpec.
func (in *VerifyTaskSpec) DeepCopy() *VerifyTaskSpec {
	if in == nil {
		return nil
	}
	out := new(VerifyTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyTaskStatus) DeepCopyInto(out *VerifyTaskStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Report != nil {
		in, out := &in.Report, &out.Report
		*out = new(VerifyReport)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyTaskStatus.
func (in *VerifyTaskStatus) DeepCopy() *VerifyTaskStatus {
	if in == nil {
		return nil
	}
	out := new(VerifyTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifyTaskSubmission) DeepCopyInto(out *VerifyTaskSubmission) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifyTaskSubmission.
func (in *VerifyTaskSubmission) DeepCopy() *VerifyTaskSubmission {
	if in == nil {
		return nil
	}
	out := new(VerifyTaskSubmission)
	in.DeepCopyInto(out)
	return out
}
