// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: breakfix.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BreakfixClient is the client API for Breakfix service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BreakfixClient interface {
	// User
	WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error)
	// Challenges
	ListChallenges(ctx context.Context, in *ListChallengesRequest, opts ...grpc.CallOption) (*ListChallengesResponse, error)
	// Instances
	StartChallenge(ctx context.Context, in *StartChallengeRequest, opts ...grpc.CallOption) (*StartChallengeResponse, error)
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	PingInstance(ctx context.Context, in *PingInstanceRequest, opts ...grpc.CallOption) (*PingInstanceResponse, error)
	StopChallenge(ctx context.Context, in *StopChallengeRequest, opts ...grpc.CallOption) (*StopChallengeResponse, error)
	// Submission
	SubmitChallenge(ctx context.Context, in *SubmitChallengeRequest, opts ...grpc.CallOption) (*SubmitChallengeResponse, error)
}

type breakfixClient struct {
	cc grpc.ClientConnInterface
}

func NewBreakfixClient(cc grpc.ClientConnInterface) BreakfixClient {
	return &breakfixClient{cc}
}

func (c *breakfixClient) WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error) {
	out := new(WhoAmIResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/WhoAmI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breakfixClient) ListChallenges(ctx context.Context, in *ListChallengesRequest, opts ...grpc.CallOption) (*ListChallengesResponse, error) {
	out := new(ListChallengesResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/ListChallenges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breakfixClient) StartChallenge(ctx context.Context, in *StartChallengeRequest, opts ...grpc.CallOption) (*StartChallengeResponse, error) {
	out := new(StartChallengeResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/StartChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breakfixClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/GetInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breakfixClient) PingInstance(ctx context.Context, in *PingInstanceRequest, opts ...grpc.CallOption) (*PingInstanceResponse, error) {
	out := new(PingInstanceResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/PingInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breakfixClient) StopChallenge(ctx context.Context, in *StopChallengeRequest, opts ...grpc.CallOption) (*StopChallengeResponse, error) {
	out := new(StopChallengeResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/StopChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breakfixClient) SubmitChallenge(ctx context.Context, in *SubmitChallengeRequest, opts ...grpc.CallOption) (*SubmitChallengeResponse, error) {
	out := new(SubmitChallengeResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/SubmitChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BreakfixServer is the server API for Breakfix service.
// All implementations must embed UnimplementedBreakfixServer
// for forward compatibility
type BreakfixServer interface {
	// User
	WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error)
	// Challenges
	ListChallenges(context.Context, *ListChallengesRequest) (*ListChallengesResponse, error)
	// Instances
	StartChallenge(context.Context, *StartChallengeRequest) (*StartChallengeResponse, error)
	GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	PingInstance(context.Context, *PingInstanceRequest) (*PingInstanceResponse, error)
	StopChallenge(context.Context, *StopChallengeRequest) (*StopChallengeResponse, error)
	// Submission
	SubmitChallenge(context.Context, *SubmitChallengeRequest) (*SubmitChallengeResponse, error)
	mustEmbedUnimplementedBreakfixServer()
}

// UnimplementedBreakfixServer must be embedded to have forward compatible implementations.
type UnimplementedBreakfixServer struct {
}

func (UnimplementedBreakfixServer) WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhoAmI not implemented")
}
func (UnimplementedBreakfixServer) ListChallenges(context.Context, *ListChallengesRequest) (*ListChallengesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChallenges not implemented")
}
func (UnimplementedBreakfixServer) StartChallenge(context.Context, *StartChallengeRequest) (*StartChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartChallenge not implemented")
}
func (UnimplementedBreakfixServer) GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedBreakfixServer) PingInstance(context.Context, *PingInstanceRequest) (*PingInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingInstance not implemented")
}
func (UnimplementedBreakfixServer) StopChallenge(context.Context, *StopChallengeRequest) (*StopChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopChallenge not implemented")
}
func (UnimplementedBreakfixServer) SubmitChallenge(context.Context, *SubmitChallengeRequest) (*SubmitChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitChallenge not implemented")
}
func (UnimplementedBreakfixServer) mustEmbedUnimplementedBreakfixServer() {}

// UnsafeBreakfixServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BreakfixServer will
// result in compilation errors.
type UnsafeBreakfixServer interface {
	mustEmbedUnimplementedBreakfixServer()
}

func RegisterBreakfixServer(s grpc.ServiceRegistrar, srv BreakfixServer) {
	s.RegisterService(&Breakfix_ServiceDesc, srv)
}

func _Breakfix_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoAmIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/WhoAmI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).WhoAmI(ctx, req.(*WhoAmIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breakfix_ListChallenges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChallengesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).ListChallenges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/ListChallenges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).ListChallenges(ctx, req.(*ListChallengesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breakfix_StartChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).StartChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/StartChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).StartChallenge(ctx, req.(*StartChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breakfix_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/GetInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breakfix_PingInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).PingInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/PingInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).PingInstance(ctx, req.(*PingInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breakfix_StopChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).StopChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/StopChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).StopChallenge(ctx, req.(*StopChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breakfix_SubmitChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).SubmitChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/SubmitChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).SubmitChallenge(ctx, req.(*SubmitChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Breakfix_ServiceDesc is the grpc.ServiceDesc for Breakfix service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Breakfix_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "breakfix.Breakfix",
	HandlerType: (*BreakfixServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WhoAmI",
			Handler:    _Breakfix_WhoAmI_Handler,
		},
		{
			MethodName: "ListChallenges",
			Handler:    _Breakfix_ListChallenges_Handler,
		},
		{
			MethodName: "StartChallenge",
			Handler:    _Breakfix_StartChallenge_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _Breakfix_GetInstance_Handler,
		},
		{
			MethodName: "PingInstance",
			Handler:    _Breakfix_PingInstance_Handler,
		},
		{
			MethodName: "StopChallenge",
			Handler:    _Breakfix_StopChallenge_Handler,
		},
		{
			MethodName: "SubmitChallenge",
			Handler:    _Breakfix_SubmitChallenge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breakfix.proto",
}
