apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: breakfix-system

resources:
  - deploy/crds/breakfix.dev_runtimeenvironments.yaml
  - deploy/crds/breakfix.dev_generatorworkspaces.yaml
  - deploy/manifests/namespace.yaml
  - deploy/manifests/rbac.yaml
  - deploy/manifests/runtime-worker-network-policy.yaml
  - deploy/manifests/postgresql.yaml
  - deploy/manifests/server-data.yaml
  - deploy/manifests/server.yaml
  - deploy/manifests/controller.yaml
  - deploy/manifests/runtime-worker.yaml

configMapGenerator:
  - name: breakfix-config
    files:
      - config.yaml=config/app/in-cluster.yaml
