//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointResultStatus) DeepCopyInto(out *CheckpointResultStatus) {
	*out = *in
	if in.FirstPassedAt != nil {
		in, out := &in.FirstPassedAt, &out.FirstPassedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointResultStatus.
func (in *CheckpointResultStatus) DeepCopy() *CheckpointResultStatus {
	if in == nil {
		return nil
	}
	out := new(CheckpointResultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointStatus) DeepCopyInto(out *CheckpointStatus) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]CheckpointResultStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CheckedAt != nil {
		in, out := &in.CheckedAt, &out.CheckedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointStatus.
func (in *CheckpointStatus) DeepCopy() *CheckpointStatus {
	if in == nil {
		return nil
	}
	out := new(CheckpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentCheckpointSpec) DeepCopyInto(out *EnvironmentCheckpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentCheckpointSpec.
func (in *EnvironmentCheckpointSpec) DeepCopy() *EnvironmentCheckpointSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentCheckpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentFailureStatus) DeepCopyInto(out *EnvironmentFailureStatus) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentFailureStatus.
func (in *EnvironmentFailureStatus) DeepCopy() *EnvironmentFailureStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentFailureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentLifecycleSpec) DeepCopyInto(out *EnvironmentLifecycleSpec) {
	*out = *in
	if in.ActivityAt != nil {
		in, out := &in.ActivityAt, &out.ActivityAt
		*out = (*in).DeepCopy()
	}
	if in.DeadlineAt != nil {
		in, out := &in.DeadlineAt, &out.DeadlineAt
		*out = (*in).DeepCopy()
	}
	if in.IdleTTLSeconds != nil {
		in, out := &in.IdleTTLSeconds, &out.IdleTTLSeconds
		*out = new(int64)
		**out = **in
	}
	if in.DrainGracePeriodSeconds != nil {
		in, out := &in.DrainGracePeriodSeconds, &out.DrainGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentLifecycleSpec.
func (in *EnvironmentLifecycleSpec) DeepCopy() *EnvironmentLifecycleSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentLifecycleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentSourceSpec) DeepCopyInto(out *EnvironmentSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentSourceSpec.
func (in *EnvironmentSourceSpec) DeepCopy() *EnvironmentSourceSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentSpec) DeepCopyInto(out *EnvironmentSpec) {
	*out = *in
	out.Source = in.Source
	if in.Checkpoints != nil {
		in, out := &in.Checkpoints, &out.Checkpoints
		*out = make([]EnvironmentCheckpointSpec, len(*in))
		copy(*out, *in)
	}
	in.Lifecycle.DeepCopyInto(&out.Lifecycle)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentSpec.
func (in *EnvironmentSpec) DeepCopy() *EnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentStatus) DeepCopyInto(out *EnvironmentStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.ReadyAt != nil {
		in, out := &in.ReadyAt, &out.ReadyAt
		*out = (*in).DeepCopy()
	}
	if in.LastActivityAt != nil {
		in, out := &in.LastActivityAt, &out.LastActivityAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.DestroyedAt != nil {
		in, out := &in.DestroyedAt, &out.DestroyedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Failure != nil {
		in, out := &in.Failure, &out.Failure
		*out = new(EnvironmentFailureStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Checkpoints != nil {
		in, out := &in.Checkpoints, &out.Checkpoints
		*out = new(CheckpointStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentStatus.
func (in *EnvironmentStatus) DeepCopy() *EnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeEnvironment) DeepCopyInto(out *NodeEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeEnvironment.
func (in *NodeEnvironment) DeepCopy() *NodeEnvironment {
	if in == nil {
		return nil
	}
	out := new(NodeEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeEnvironmentList) DeepCopyInto(out *NodeEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeEnvironmentList.
func (in *NodeEnvironmentList) DeepCopy() *NodeEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(NodeEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeEnvironmentSpec) DeepCopyInto(out *NodeEnvironmentSpec) {
	*out = *in
	in.Environment.DeepCopyInto(&out.Environment)
	in.Runtime.DeepCopyInto(&out.Runtime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeEnvironmentSpec.
func (in *NodeEnvironmentSpec) DeepCopy() *NodeEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(NodeEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeEnvironmentStatus) DeepCopyInto(out *NodeEnvironmentStatus) {
	*out = *in
	in.Environment.DeepCopyInto(&out.Environment)
	in.Runtime.DeepCopyInto(&out.Runtime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeEnvironmentStatus.
func (in *NodeEnvironmentStatus) DeepCopy() *NodeEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(NodeEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInstanceStatus) DeepCopyInto(out *NodeInstanceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInstanceStatus.
func (in *NodeInstanceStatus) DeepCopy() *NodeInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(NodeInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceSnapshot) DeepCopyInto(out *NodeResourceSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceSnapshot.
func (in *NodeResourceSnapshot) DeepCopy() *NodeResourceSnapshot {
	if in == nil {
		return nil
	}
	out := new(NodeResourceSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRuntimeNodeSpec) DeepCopyInto(out *NodeRuntimeNodeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRuntimeNodeSpec.
func (in *NodeRuntimeNodeSpec) DeepCopy() *NodeRuntimeNodeSpec {
	if in == nil {
		return nil
	}
	out := new(NodeRuntimeNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRuntimeSnapshot) DeepCopyInto(out *NodeRuntimeSnapshot) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeRuntimeNodeSpec, len(*in))
		copy(*out, *in)
	}
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRuntimeSnapshot.
func (in *NodeRuntimeSnapshot) DeepCopy() *NodeRuntimeSnapshot {
	if in == nil {
		return nil
	}
	out := new(NodeRuntimeSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRuntimeStatus) DeepCopyInto(out *NodeRuntimeStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeInstanceStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRuntimeStatus.
func (in *NodeRuntimeStatus) DeepCopy() *NodeRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sEnvironment) DeepCopyInto(out *VK8sEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sEnvironment.
func (in *VK8sEnvironment) DeepCopy() *VK8sEnvironment {
	if in == nil {
		return nil
	}
	out := new(VK8sEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VK8sEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sEnvironmentList) DeepCopyInto(out *VK8sEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VK8sEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sEnvironmentList.
func (in *VK8sEnvironmentList) DeepCopy() *VK8sEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(VK8sEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VK8sEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sEnvironmentSpec) DeepCopyInto(out *VK8sEnvironmentSpec) {
	*out = *in
	in.Environment.DeepCopyInto(&out.Environment)
	in.Runtime.DeepCopyInto(&out.Runtime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sEnvironmentSpec.
func (in *VK8sEnvironmentSpec) DeepCopy() *VK8sEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(VK8sEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sEnvironmentStatus) DeepCopyInto(out *VK8sEnvironmentStatus) {
	*out = *in
	in.Environment.DeepCopyInto(&out.Environment)
	out.Runtime = in.Runtime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sEnvironmentStatus.
func (in *VK8sEnvironmentStatus) DeepCopy() *VK8sEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(VK8sEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sNetworkSnapshot) DeepCopyInto(out *VK8sNetworkSnapshot) {
	*out = *in
	if in.ProtectedCIDRs != nil {
		in, out := &in.ProtectedCIDRs, &out.ProtectedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sNetworkSnapshot.
func (in *VK8sNetworkSnapshot) DeepCopy() *VK8sNetworkSnapshot {
	if in == nil {
		return nil
	}
	out := new(VK8sNetworkSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sResourceSnapshot) DeepCopyInto(out *VK8sResourceSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sResourceSnapshot.
func (in *VK8sResourceSnapshot) DeepCopy() *VK8sResourceSnapshot {
	if in == nil {
		return nil
	}
	out := new(VK8sResourceSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sRuntimeSnapshot) DeepCopyInto(out *VK8sRuntimeSnapshot) {
	*out = *in
	out.Resources = in.Resources
	in.Network.DeepCopyInto(&out.Network)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sRuntimeSnapshot.
func (in *VK8sRuntimeSnapshot) DeepCopy() *VK8sRuntimeSnapshot {
	if in == nil {
		return nil
	}
	out := new(VK8sRuntimeSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VK8sRuntimeStatus) DeepCopyInto(out *VK8sRuntimeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VK8sRuntimeStatus.
func (in *VK8sRuntimeStatus) DeepCopy() *VK8sRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(VK8sRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}
