apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - worker-network-policy.yaml
  - postgresql.yaml
  - server-data.yaml
  - server.yaml
  - controller.yaml
  - generate-worker.yaml
  - taxonomy-worker.yaml
