package postgres

var schemaCatalogStatements = []string{
	`CREATE TABLE catalog_releases (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		version TEXT NOT NULL,
		bundle_digest TEXT NOT NULL UNIQUE,
		source_digest TEXT NOT NULL,
		state TEXT NOT NULL CHECK (state IN ('Pending', 'Installing', 'Committing', 'Ready', 'Failed')),
		deadline_at TIMESTAMPTZ NOT NULL,
		commit_id TEXT NOT NULL DEFAULT '',
		lease_owner TEXT NOT NULL DEFAULT '',
		lease_expires_at TIMESTAMPTZ,
		last_error TEXT NOT NULL DEFAULT '',
		created_at TIMESTAMPTZ NOT NULL,
		updated_at TIMESTAMPTZ NOT NULL,
		CHECK ((lease_owner = '') = (lease_expires_at IS NULL)),
		CHECK ((state NOT IN ('Committing', 'Ready')) OR commit_id <> '')
	)`,
	`CREATE INDEX catalog_releases_recovery ON catalog_releases(state, deadline_at, created_at, id)`,
	`CREATE TABLE catalog_release_entries (
		id TEXT PRIMARY KEY,
		release_id TEXT NOT NULL REFERENCES catalog_releases(id) ON DELETE RESTRICT,
		source_path TEXT NOT NULL,
		source_ref TEXT NOT NULL,
		title TEXT NOT NULL,
		content_revision TEXT NOT NULL,
		archive_sha256 TEXT NOT NULL,
		execution_snapshot JSONB NOT NULL,
		state TEXT NOT NULL CHECK (state IN ('Pending', 'Building', 'ArtifactPublishing', 'Verifying', 'ReadyToCommit', 'Failed')),
		attempt INTEGER NOT NULL DEFAULT 0 CHECK (attempt >= 0),
		lease_owner TEXT NOT NULL DEFAULT '',
		lease_expires_at TIMESTAMPTZ,
		next_run_at TIMESTAMPTZ NOT NULL,
		build_output JSONB,
		artifact_reference JSONB,
		verify_environment JSONB,
		verification_report JSONB,
		last_error TEXT NOT NULL DEFAULT '',
		created_at TIMESTAMPTZ NOT NULL,
		updated_at TIMESTAMPTZ NOT NULL,
		UNIQUE(release_id, source_path),
		UNIQUE(release_id, source_ref),
		CHECK ((lease_owner = '') = (lease_expires_at IS NULL))
	)`,
	`CREATE INDEX catalog_release_entries_claim ON catalog_release_entries(state, next_run_at, lease_expires_at, created_at, id)`,
	`CREATE INDEX catalog_release_entries_source_ref ON catalog_release_entries(source_ref, content_revision)`,
	`CREATE TABLE catalog_release_entry_commits (
		id TEXT PRIMARY KEY,
		release_id TEXT NOT NULL REFERENCES catalog_releases(id) ON DELETE RESTRICT,
		entry_id TEXT NOT NULL UNIQUE REFERENCES catalog_release_entries(id) ON DELETE RESTRICT,
		challenge_id TEXT NOT NULL UNIQUE,
		source_slug TEXT NOT NULL UNIQUE,
		state TEXT NOT NULL CHECK (state IN ('Pending', 'Prepared', 'ArtifactPublished', 'Materialized', 'Committed')),
		artifact_reference JSONB,
		materialized_at TIMESTAMPTZ,
		committed_at TIMESTAMPTZ,
		created_at TIMESTAMPTZ NOT NULL,
		updated_at TIMESTAMPTZ NOT NULL
	)`,
	`CREATE INDEX catalog_release_entry_commits_release ON catalog_release_entry_commits(release_id, state, entry_id)`,
	`CREATE TABLE roadmap_entries (
		challenge_id TEXT PRIMARY KEY,
		topic_id TEXT NOT NULL,
		topic_processed BOOLEAN NOT NULL,
		challenge_processed BOOLEAN NOT NULL,
		created_at TIMESTAMPTZ NOT NULL
	)`,
}
