// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// ChallengeList defines model for ChallengeList.
type ChallengeList struct {
	Challenges *[]ChallengeSummary `json:"challenges,omitempty"`
}

// ChallengeSummary defines model for ChallengeSummary.
type ChallengeSummary struct {
	Active     *bool     `json:"active,omitempty"`
	Difficulty *string   `json:"difficulty,omitempty"`
	Id         *string   `json:"id,omitempty"`
	Solved     *bool     `json:"solved,omitempty"`
	Tags       *[]string `json:"tags,omitempty"`
	Title      *string   `json:"title,omitempty"`
	Type       *string   `json:"type,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	Topic string `json:"topic"`
}

// GenerateResponse defines model for GenerateResponse.
type GenerateResponse struct {
	ChallengeId *string `json:"challenge_id,omitempty"`
	Detail      *string `json:"detail,omitempty"`
	Status      *string `json:"status,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	TotpCode string `json:"totp_code"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Name *string `json:"name,omitempty"`

	// Token JWT access token
	Token  *string `json:"token,omitempty"`
	UserId *string `json:"user_id,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	TotpSecret *string `json:"totp_secret,omitempty"`
	TotpUrl    *string `json:"totp_url,omitempty"`
}

// ResetResponse defines model for ResetResponse.
type ResetResponse struct {
	ChallengeTitle *string `json:"challenge_title,omitempty"`
}

// StartResponse defines model for StartResponse.
type StartResponse struct {
	ChallengeTitle *string `json:"challenge_title,omitempty"`
}

// SubmitResponse defines model for SubmitResponse.
type SubmitResponse struct {
	ExitCode *int    `json:"exit_code,omitempty"`
	Output   *string `json:"output,omitempty"`
	Passed   *bool   `json:"passed,omitempty"`
}

// Error defines model for Error.
type Error = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// GenerateChallengeJSONRequestBody defines body for GenerateChallenge for application/json ContentType.
type GenerateChallengeJSONRequestBody = GenerateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with password + TOTP
	// (POST /auth/login)
	Login(c *gin.Context)
	// Register a new user
	// (POST /auth/register)
	Register(c *gin.Context)
	// List all challenges
	// (GET /challenges)
	ListChallenges(c *gin.Context)
	// Reset challenge to initial state
	// (POST /challenges/{id}/reset)
	ResetChallenge(c *gin.Context, id string)
	// Start or resume a challenge instance
	// (POST /challenges/{id}/start)
	StartChallenge(c *gin.Context, id string)
	// Submit solution for verification
	// (POST /challenges/{id}/submit)
	SubmitChallenge(c *gin.Context, id string)
	// Generate a new challenge (admin)
	// (POST /generate)
	GenerateChallenge(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// ListChallenges operation middleware
func (siw *ServerInterfaceWrapper) ListChallenges(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListChallenges(c)
}

// ResetChallenge operation middleware
func (siw *ServerInterfaceWrapper) ResetChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResetChallenge(c, id)
}

// StartChallenge operation middleware
func (siw *ServerInterfaceWrapper) StartChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartChallenge(c, id)
}

// SubmitChallenge operation middleware
func (siw *ServerInterfaceWrapper) SubmitChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubmitChallenge(c, id)
}

// GenerateChallenge operation middleware
func (siw *ServerInterfaceWrapper) GenerateChallenge(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GenerateChallenge(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.GET(options.BaseURL+"/challenges", wrapper.ListChallenges)
	router.POST(options.BaseURL+"/challenges/:id/reset", wrapper.ResetChallenge)
	router.POST(options.BaseURL+"/challenges/:id/start", wrapper.StartChallenge)
	router.POST(options.BaseURL+"/challenges/:id/submit", wrapper.SubmitChallenge)
	router.POST(options.BaseURL+"/generate", wrapper.GenerateChallenge)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fdfb9s2EP8qBLeHDRMipy0GVG9t1w0ZArRIMuwhMApGOstsKVI9npwagb77QFKyJZtynCIe0DdJPN6f",
	"3+/+6YHnpqqNBk2WZw8cwdZGW/Av7xENuofcaAJN7lHUtZK5IGl0+tka7b7ZfAmVcE8/Iyx4xn9Kt1rT",
	"cGpTr+2q08/btk14ATZHWTtlPOvMue/dFafx3VIoBbqES2m9AzWaGpBkcDHvj/2bJKjsY35sNF43VSVw",
	"zduE07oGnnGBKNbeg+6DufsMOTmJvVt7roic5ArcU3f5zhgFQrvbhVwsZN4oWg/OLaHUpTuWRfSzNWoF",
	"RVwjiXIc8t7tcUwJJ0kKDkjuHcRgGJO4hwH0GbOvCuFrI9GFc9uJzSP6/wINKAiu4GsDMcLJ1DJ/3EIQ",
	"O2xhKohNTn2a4KUAElLFKSNBjT0SzEtTSj0ZaS2svTcYd4EM1Z9yU8QJbSygFhU8jtNGMtnaG2qfT7s9",
	"Bd+EYaf1C/h+MS77v/+9YSLPwVoWJJJ4QHE2YrheQSktAR4FbSX1JeiSljz7PTkM5UD0RfIdwM4P+jqF",
	"pyfDQo5A06nQoDoaHAt0TPJP9YuY0msS+PxKm7tKHtAK3yTt1oDUBCWgu24aqps4ZI6ReGPd98MVNeQN",
	"SlpfuwkSbN+BQMA3jcuF/u1Pg5WgkNG8G2JeuT/dpvWSqA7zT+qF2S+I66v36R+w+lBb5sLBlYR7VqOb",
	"LzmwWglaGKz4pqPztwjiy0J+Y28+XvCErwBt0HR+NjubeSxq0KKWPOMvz2ZnL31S0tJHkoqGlqlyNe0h",
	"NqFgHNB+yl8UPAslz0OGg6W3plg/214w6oLtuI4IG/AfBlvJi9nsuW1P7yRegNnG96dFoxKGQA1qy1zb",
	"Cv2qTfir2fmUqY3v6WC/6XeITv+9pCXr2wT7jd18uPnI+xl/yx1DfO4uBrKw6xnTfPVd5USU7TbYo1g7",
	"P4H5aeL+sYCsBwqKQNLs+0jq7THBNNwz19rj7Iy30RJilSQtvduKnTC3x5tzBKKNAFNBYtvpeHY77nG3",
	"83Y+yltpiQmlWD6MpYdk8HEXmPRBFq3DO4Azlb4Wtij5boWiAgK03jPXqnwH40m3brgVejcFkwFQu+Nm",
	"fkLgxxP2IPABB5+br56Um8fy5H3ZksTIMKklSaGYW1VhQJrUloTOJzmzbsZPc+ZXgB+Ws/ECE+HsokOH",
	"IYhifUrKvCvMuO5lmwqYGNDXc/QU2vwWdYA3f/7jEjdeEiPMeQnrNiKPqDppvQV3mDWqcebZwiBbAcpF",
	"F90B4srux3Saqv7XdUjWKcb77k/4/7yU7f2hR0jtZIakPoWm3kQ30bcF9osoKql/HY730gU0b4N+XPVl",
	"sbsn5kKxAlY84f5fzG/5WZoqd7A0lrLXs9ez1C3h7bz9LwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
