// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AssistantMessageRole.
const (
	AssistantMessageRoleAssistant AssistantMessageRole = "assistant"
	AssistantMessageRoleUser      AssistantMessageRole = "user"
)

// Valid indicates whether the value is a known member of the AssistantMessageRole enum.
func (e AssistantMessageRole) Valid() bool {
	switch e {
	case AssistantMessageRoleAssistant:
		return true
	case AssistantMessageRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for AssistantTurnStatus.
const (
	AssistantTurnStatusCompleted AssistantTurnStatus = "completed"
	AssistantTurnStatusFailed    AssistantTurnStatus = "failed"
	AssistantTurnStatusRunning   AssistantTurnStatus = "running"
)

// Valid indicates whether the value is a known member of the AssistantTurnStatus enum.
func (e AssistantTurnStatus) Valid() bool {
	switch e {
	case AssistantTurnStatusCompleted:
		return true
	case AssistantTurnStatusFailed:
		return true
	case AssistantTurnStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for AuthoringMessageRole.
const (
	AuthoringMessageRoleAgent  AuthoringMessageRole = "agent"
	AuthoringMessageRoleEvent  AuthoringMessageRole = "event"
	AuthoringMessageRoleSystem AuthoringMessageRole = "system"
	AuthoringMessageRoleUser   AuthoringMessageRole = "user"
)

// Valid indicates whether the value is a known member of the AuthoringMessageRole enum.
func (e AuthoringMessageRole) Valid() bool {
	switch e {
	case AuthoringMessageRoleAgent:
		return true
	case AuthoringMessageRoleEvent:
		return true
	case AuthoringMessageRoleSystem:
		return true
	case AuthoringMessageRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for AuthoringMetadataDifficulty.
const (
	AuthoringMetadataDifficultyEasy   AuthoringMetadataDifficulty = "easy"
	AuthoringMetadataDifficultyHard   AuthoringMetadataDifficulty = "hard"
	AuthoringMetadataDifficultyMedium AuthoringMetadataDifficulty = "medium"
)

// Valid indicates whether the value is a known member of the AuthoringMetadataDifficulty enum.
func (e AuthoringMetadataDifficulty) Valid() bool {
	switch e {
	case AuthoringMetadataDifficultyEasy:
		return true
	case AuthoringMetadataDifficultyHard:
		return true
	case AuthoringMetadataDifficultyMedium:
		return true
	default:
		return false
	}
}

// Defines values for AuthoringMetadataRuntime.
const (
	AuthoringMetadataRuntimeContainer AuthoringMetadataRuntime = "container"
	AuthoringMetadataRuntimeVcluster  AuthoringMetadataRuntime = "vcluster"
)

// Valid indicates whether the value is a known member of the AuthoringMetadataRuntime enum.
func (e AuthoringMetadataRuntime) Valid() bool {
	switch e {
	case AuthoringMetadataRuntimeContainer:
		return true
	case AuthoringMetadataRuntimeVcluster:
		return true
	default:
		return false
	}
}

// Defines values for AuthoringSessionState.
const (
	AuthoringSessionStateAwaitingVerifiedReview           AuthoringSessionState = "AwaitingVerifiedReview"
	AuthoringSessionStateDraftConversation                AuthoringSessionState = "DraftConversation"
	AuthoringSessionStateGeneratingAndVerifying           AuthoringSessionState = "GeneratingAndVerifying"
	AuthoringSessionStateIntentReview                     AuthoringSessionState = "IntentReview"
	AuthoringSessionStatePublished                        AuthoringSessionState = "Published"
	AuthoringSessionStatePublishing                       AuthoringSessionState = "Publishing"
	AuthoringSessionStateRevisingAndVerifying             AuthoringSessionState = "RevisingAndVerifying"
	AuthoringSessionStateVerificationInfrastructureFailed AuthoringSessionState = "VerificationInfrastructureFailed"
)

// Valid indicates whether the value is a known member of the AuthoringSessionState enum.
func (e AuthoringSessionState) Valid() bool {
	switch e {
	case AuthoringSessionStateAwaitingVerifiedReview:
		return true
	case AuthoringSessionStateDraftConversation:
		return true
	case AuthoringSessionStateGeneratingAndVerifying:
		return true
	case AuthoringSessionStateIntentReview:
		return true
	case AuthoringSessionStatePublished:
		return true
	case AuthoringSessionStatePublishing:
		return true
	case AuthoringSessionStateRevisingAndVerifying:
		return true
	case AuthoringSessionStateVerificationInfrastructureFailed:
		return true
	default:
		return false
	}
}

// Defines values for AuthoringVerificationReportClass.
const (
	Artifact       AuthoringVerificationReportClass = "artifact"
	Infrastructure AuthoringVerificationReportClass = "infrastructure"
)

// Valid indicates whether the value is a known member of the AuthoringVerificationReportClass enum.
func (e AuthoringVerificationReportClass) Valid() bool {
	switch e {
	case Artifact:
		return true
	case Infrastructure:
		return true
	default:
		return false
	}
}

// Defines values for ChallengeSummaryDifficulty.
const (
	ChallengeSummaryDifficultyEasy   ChallengeSummaryDifficulty = "easy"
	ChallengeSummaryDifficultyHard   ChallengeSummaryDifficulty = "hard"
	ChallengeSummaryDifficultyMedium ChallengeSummaryDifficulty = "medium"
)

// Valid indicates whether the value is a known member of the ChallengeSummaryDifficulty enum.
func (e ChallengeSummaryDifficulty) Valid() bool {
	switch e {
	case ChallengeSummaryDifficultyEasy:
		return true
	case ChallengeSummaryDifficultyHard:
		return true
	case ChallengeSummaryDifficultyMedium:
		return true
	default:
		return false
	}
}

// Defines values for ChallengeSummaryRuntime.
const (
	ChallengeSummaryRuntimeContainer ChallengeSummaryRuntime = "container"
	ChallengeSummaryRuntimeVcluster  ChallengeSummaryRuntime = "vcluster"
)

// Valid indicates whether the value is a known member of the ChallengeSummaryRuntime enum.
func (e ChallengeSummaryRuntime) Valid() bool {
	switch e {
	case ChallengeSummaryRuntimeContainer:
		return true
	case ChallengeSummaryRuntimeVcluster:
		return true
	default:
		return false
	}
}

// Defines values for MySpaceActiveEnvironmentRuntime.
const (
	MySpaceActiveEnvironmentRuntimeContainer MySpaceActiveEnvironmentRuntime = "container"
	MySpaceActiveEnvironmentRuntimeVcluster  MySpaceActiveEnvironmentRuntime = "vcluster"
)

// Valid indicates whether the value is a known member of the MySpaceActiveEnvironmentRuntime enum.
func (e MySpaceActiveEnvironmentRuntime) Valid() bool {
	switch e {
	case MySpaceActiveEnvironmentRuntimeContainer:
		return true
	case MySpaceActiveEnvironmentRuntimeVcluster:
		return true
	default:
		return false
	}
}

// Defines values for MySpaceAuthoringDraftState.
const (
	MySpaceAuthoringDraftStateAwaitingVerifiedReview           MySpaceAuthoringDraftState = "AwaitingVerifiedReview"
	MySpaceAuthoringDraftStateDraftConversation                MySpaceAuthoringDraftState = "DraftConversation"
	MySpaceAuthoringDraftStateGeneratingAndVerifying           MySpaceAuthoringDraftState = "GeneratingAndVerifying"
	MySpaceAuthoringDraftStateIntentReview                     MySpaceAuthoringDraftState = "IntentReview"
	MySpaceAuthoringDraftStatePublished                        MySpaceAuthoringDraftState = "Published"
	MySpaceAuthoringDraftStatePublishing                       MySpaceAuthoringDraftState = "Publishing"
	MySpaceAuthoringDraftStateRevisingAndVerifying             MySpaceAuthoringDraftState = "RevisingAndVerifying"
	MySpaceAuthoringDraftStateVerificationInfrastructureFailed MySpaceAuthoringDraftState = "VerificationInfrastructureFailed"
)

// Valid indicates whether the value is a known member of the MySpaceAuthoringDraftState enum.
func (e MySpaceAuthoringDraftState) Valid() bool {
	switch e {
	case MySpaceAuthoringDraftStateAwaitingVerifiedReview:
		return true
	case MySpaceAuthoringDraftStateDraftConversation:
		return true
	case MySpaceAuthoringDraftStateGeneratingAndVerifying:
		return true
	case MySpaceAuthoringDraftStateIntentReview:
		return true
	case MySpaceAuthoringDraftStatePublished:
		return true
	case MySpaceAuthoringDraftStatePublishing:
		return true
	case MySpaceAuthoringDraftStateRevisingAndVerifying:
		return true
	case MySpaceAuthoringDraftStateVerificationInfrastructureFailed:
		return true
	default:
		return false
	}
}

// Defines values for MySpaceChallengeRuntime.
const (
	MySpaceChallengeRuntimeContainer MySpaceChallengeRuntime = "container"
	MySpaceChallengeRuntimeVcluster  MySpaceChallengeRuntime = "vcluster"
)

// Valid indicates whether the value is a known member of the MySpaceChallengeRuntime enum.
func (e MySpaceChallengeRuntime) Valid() bool {
	switch e {
	case MySpaceChallengeRuntimeContainer:
		return true
	case MySpaceChallengeRuntimeVcluster:
		return true
	default:
		return false
	}
}

// Defines values for MySpaceLearningHistoryState.
const (
	MySpaceLearningHistoryStateActive    MySpaceLearningHistoryState = "active"
	MySpaceLearningHistoryStateCompleted MySpaceLearningHistoryState = "completed"
	MySpaceLearningHistoryStateExpired   MySpaceLearningHistoryState = "expired"
	MySpaceLearningHistoryStateReset     MySpaceLearningHistoryState = "reset"
	MySpaceLearningHistoryStateStopped   MySpaceLearningHistoryState = "stopped"
)

// Valid indicates whether the value is a known member of the MySpaceLearningHistoryState enum.
func (e MySpaceLearningHistoryState) Valid() bool {
	switch e {
	case MySpaceLearningHistoryStateActive:
		return true
	case MySpaceLearningHistoryStateCompleted:
		return true
	case MySpaceLearningHistoryStateExpired:
		return true
	case MySpaceLearningHistoryStateReset:
		return true
	case MySpaceLearningHistoryStateStopped:
		return true
	default:
		return false
	}
}

// Defines values for MySpacePublishedChallengeTaxonomyStatus.
const (
	Blocked  MySpacePublishedChallengeTaxonomyStatus = "blocked"
	Mapped   MySpacePublishedChallengeTaxonomyStatus = "mapped"
	Mapping  MySpacePublishedChallengeTaxonomyStatus = "mapping"
	Retrying MySpacePublishedChallengeTaxonomyStatus = "retrying"
)

// Valid indicates whether the value is a known member of the MySpacePublishedChallengeTaxonomyStatus enum.
func (e MySpacePublishedChallengeTaxonomyStatus) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Mapped:
		return true
	case Mapping:
		return true
	case Retrying:
		return true
	default:
		return false
	}
}

// Defines values for GetMySpaceLearningParamsState.
const (
	Active    GetMySpaceLearningParamsState = "active"
	Completed GetMySpaceLearningParamsState = "completed"
	Ended     GetMySpaceLearningParamsState = "ended"
)

// Valid indicates whether the value is a known member of the GetMySpaceLearningParamsState enum.
func (e GetMySpaceLearningParamsState) Valid() bool {
	switch e {
	case Active:
		return true
	case Completed:
		return true
	case Ended:
		return true
	default:
		return false
	}
}

// Defines values for GetMySpaceLearningParamsRuntime.
const (
	Container GetMySpaceLearningParamsRuntime = "container"
	Vcluster  GetMySpaceLearningParamsRuntime = "vcluster"
)

// Valid indicates whether the value is a known member of the GetMySpaceLearningParamsRuntime enum.
func (e GetMySpaceLearningParamsRuntime) Valid() bool {
	switch e {
	case Container:
		return true
	case Vcluster:
		return true
	default:
		return false
	}
}

// AssistantConversation defines model for AssistantConversation.
type AssistantConversation struct {
	ActiveTurn  *AssistantTurn     `json:"active_turn,omitempty"`
	ChallengeId string             `json:"challenge_id"`
	Id          string             `json:"id"`
	Messages    []AssistantMessage `json:"messages"`
}

// AssistantEvidence defines model for AssistantEvidence.
type AssistantEvidence struct {
	Kind  string `json:"kind"`
	Label string `json:"label"`
}

// AssistantMessage defines model for AssistantMessage.
type AssistantMessage struct {
	Content   string               `json:"content"`
	CreatedAt string               `json:"created_at"`
	Evidence  *[]AssistantEvidence `json:"evidence,omitempty"`
	Id        string               `json:"id"`
	Role      AssistantMessageRole `json:"role"`
}

// AssistantMessageRole defines model for AssistantMessage.Role.
type AssistantMessageRole string

// AssistantMessageRequest defines model for AssistantMessageRequest.
type AssistantMessageRequest struct {
	Content       string   `json:"content"`
	CurrentWindow string   `json:"current_window"`
	OpenWindows   []string `json:"open_windows"`
}

// AssistantTurn defines model for AssistantTurn.
type AssistantTurn struct {
	Content   string               `json:"content"`
	CreatedAt string               `json:"created_at"`
	Error     *string              `json:"error,omitempty"`
	Evidence  *[]AssistantEvidence `json:"evidence,omitempty"`
	Id        string               `json:"id"`
	Message   *AssistantMessage    `json:"message,omitempty"`
	SessionId string               `json:"session_id"`
	Status    AssistantTurnStatus  `json:"status"`
	UpdatedAt string               `json:"updated_at"`
}

// AssistantTurnStatus defines model for AssistantTurn.Status.
type AssistantTurnStatus string

// AuthoringArtifact defines model for AuthoringArtifact.
type AuthoringArtifact struct {
	Directory      string `json:"directory"`
	GeneratorRunId string `json:"generator_run_id"`
	SubmissionId   string `json:"submission_id"`
}

// AuthoringAsset defines model for AuthoringAsset.
type AuthoringAsset struct {
	Content string `json:"content"`
	Path    string `json:"path"`
}

// AuthoringChange defines model for AuthoringChange.
type AuthoringChange struct {
	DifficultyImpact string `json:"difficulty_impact"`
	Kind             string `json:"kind"`
	Revision         int    `json:"revision"`
	Summary          string `json:"summary"`
}

// AuthoringCheckpoint defines model for AuthoringCheckpoint.
type AuthoringCheckpoint struct {
	Id       string `json:"id"`
	Markdown string `json:"markdown"`
	Position int    `json:"position"`
	Title    string `json:"title"`
}

// AuthoringFileDiff defines model for AuthoringFileDiff.
type AuthoringFileDiff struct {
	Diff string `json:"diff"`
	Path string `json:"path"`
}

// AuthoringMessage defines model for AuthoringMessage.
type AuthoringMessage struct {
	Changes   *[]AuthoringChange   `json:"changes,omitempty"`
	Content   string               `json:"content"`
	CreatedAt time.Time            `json:"created_at"`
	Id        string               `json:"id"`
	Role      AuthoringMessageRole `json:"role"`
}

// AuthoringMessageRole defines model for AuthoringMessage.Role.
type AuthoringMessageRole string

// AuthoringMessageRequest defines model for AuthoringMessageRequest.
type AuthoringMessageRequest struct {
	Content string `json:"content"`
}

// AuthoringMetadata defines model for AuthoringMetadata.
type AuthoringMetadata struct {
	Description string                      `json:"description"`
	Difficulty  AuthoringMetadataDifficulty `json:"difficulty"`
	Runtime     AuthoringMetadataRuntime    `json:"runtime"`
	Title       string                      `json:"title"`
}

// AuthoringMetadataDifficulty defines model for AuthoringMetadata.Difficulty.
type AuthoringMetadataDifficulty string

// AuthoringMetadataRuntime defines model for AuthoringMetadata.Runtime.
type AuthoringMetadataRuntime string

// AuthoringPlan defines model for AuthoringPlan.
type AuthoringPlan struct {
	Checkpoints []AuthoringCheckpoint `json:"checkpoints"`
	Metadata    AuthoringMetadata     `json:"metadata"`
	Overview    string                `json:"overview"`
}

// AuthoringSession defines model for AuthoringSession.
type AuthoringSession struct {
	Artifact *AuthoringArtifact `json:"artifact,omitempty"`
	Assets   []AuthoringAsset   `json:"assets"`

	// AuthoringTurnActive Whether the durable authoring Agent Run is pending or running. While true, the plan is being updated privately and author actions are unavailable.
	AuthoringTurnActive bool                   `json:"authoring_turn_active"`
	Diff                []AuthoringFileDiff    `json:"diff"`
	GeneratorRunId      *string                `json:"generator_run_id,omitempty"`
	Id                  string                 `json:"id"`
	Intent              AuthoringPlan          `json:"intent"`
	IntentRevision      int                    `json:"intent_revision"`
	Messages            []AuthoringMessage     `json:"messages"`
	PublishChallengeId  *string                `json:"publish_challenge_id,omitempty"`
	State               AuthoringSessionState  `json:"state"`
	UpdatedAt           time.Time              `json:"updated_at"`
	Verification        *AuthoringVerification `json:"verification,omitempty"`
	Verified            *VerifiedChallenge     `json:"verified,omitempty"`
	VerifyTaskId        *string                `json:"verify_task_id,omitempty"`
	VisibleRevision     int                    `json:"visible_revision"`
}

// AuthoringSessionState defines model for AuthoringSession.State.
type AuthoringSessionState string

// AuthoringVerification defines model for AuthoringVerification.
type AuthoringVerification struct {
	ChallengeId *string                      `json:"challenge_id,omitempty"`
	Message     string                       `json:"message"`
	Phase       string                       `json:"phase"`
	Report      *AuthoringVerificationReport `json:"report,omitempty"`
	TaskId      string                       `json:"task_id"`
}

// AuthoringVerificationIssue defines model for AuthoringVerificationIssue.
type AuthoringVerificationIssue struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// AuthoringVerificationReport defines model for AuthoringVerificationReport.
type AuthoringVerificationReport struct {
	AnswerPassed      bool                              `json:"answer_passed"`
	BuildPassed       bool                              `json:"build_passed"`
	CheckpointsPassed bool                              `json:"checkpoints_passed"`
	Class             *AuthoringVerificationReportClass `json:"class,omitempty"`
	Issues            *[]AuthoringVerificationIssue     `json:"issues,omitempty"`
	Summary           *string                           `json:"summary,omitempty"`
}

// AuthoringVerificationReportClass defines model for AuthoringVerificationReport.Class.
type AuthoringVerificationReportClass string

// ChallengeCheckpoint defines model for ChallengeCheckpoint.
type ChallengeCheckpoint struct {
	DependsOn   *[]string `json:"depends_on,omitempty"`
	Description string    `json:"description"`
	Hint        *string   `json:"hint,omitempty"`
	Id          string    `json:"id"`
	Title       string    `json:"title"`
}

// ChallengeContent defines model for ChallengeContent.
type ChallengeContent struct {
	Checkpoints []ChallengeCheckpoint `json:"checkpoints"`
	Hints       map[string]string     `json:"hints"`
	Id          string                `json:"id"`
	Problem     string                `json:"problem"`
	Solution    string                `json:"solution"`
	Taxonomy    ChallengeTaxonomy     `json:"taxonomy"`
	Title       string                `json:"title"`
}

// ChallengeEntrySkill defines model for ChallengeEntrySkill.
type ChallengeEntrySkill struct {
	Id       string              `json:"id"`
	Requires []TaxonomyReference `json:"requires"`
	Title    string              `json:"title"`
}

// ChallengeList defines model for ChallengeList.
type ChallengeList struct {
	Challenges []ChallengeSummary `json:"challenges"`
}

// ChallengeOutcome defines model for ChallengeOutcome.
type ChallengeOutcome struct {
	Id      string `json:"id"`
	Primary bool   `json:"primary"`
	Title   string `json:"title"`
}

// ChallengeProgress defines model for ChallengeProgress.
type ChallengeProgress struct {
	Checks []CheckpointResult `json:"checks"`
}

// ChallengeSummary defines model for ChallengeSummary.
type ChallengeSummary struct {
	Active         *bool                      `json:"active,omitempty"`
	Description    string                     `json:"description"`
	Difficulty     ChallengeSummaryDifficulty `json:"difficulty"`
	Id             string                     `json:"id"`
	PrimaryOutcome TaxonomyReference          `json:"primary_outcome"`
	Progress       *CheckpointProgressSummary `json:"progress,omitempty"`
	PublishedAt    time.Time                  `json:"published_at"`
	Runtime        ChallengeSummaryRuntime    `json:"runtime"`
	Solved         *bool                      `json:"solved,omitempty"`
	Tags           []TaxonomyReference        `json:"tags"`
	Title          string                     `json:"title"`
	Type           string                     `json:"type"`
}

// ChallengeSummaryDifficulty defines model for ChallengeSummary.Difficulty.
type ChallengeSummaryDifficulty string

// ChallengeSummaryRuntime defines model for ChallengeSummary.Runtime.
type ChallengeSummaryRuntime string

// ChallengeTaxonomy defines model for ChallengeTaxonomy.
type ChallengeTaxonomy struct {
	EntrySkills    []ChallengeEntrySkill `json:"entry_skills"`
	Outcomes       []ChallengeOutcome    `json:"outcomes"`
	PrimaryOutcome TaxonomyReference     `json:"primary_outcome"`
	Revision       string                `json:"revision"`
	Tags           []TaxonomyReference   `json:"tags"`
}

// CheckpointFirstPass defines model for CheckpointFirstPass.
type CheckpointFirstPass struct {
	CheckpointId  string    `json:"checkpoint_id"`
	FirstPassedAt time.Time `json:"first_passed_at"`
	Summary       string    `json:"summary"`
}

// CheckpointProgressSummary defines model for CheckpointProgressSummary.
type CheckpointProgressSummary struct {
	Passed int `json:"passed"`
	Total  int `json:"total"`
}

// CheckpointResult defines model for CheckpointResult.
type CheckpointResult struct {
	Details       *string    `json:"details,omitempty"`
	FirstPassedAt *time.Time `json:"first_passed_at,omitempty"`
	Id            string     `json:"id"`
	Passed        bool       `json:"passed"`
	Summary       string     `json:"summary"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	TotpCode string `json:"totp_code"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Name string `json:"name"`

	// Token JWT access token
	Token  string `json:"token"`
	UserId string `json:"user_id"`
}

// MySpace defines model for MySpace.
type MySpace struct {
	ActiveEnvironments       []MySpaceActiveEnvironment `json:"active_environments"`
	Authoring                MySpaceAuthoring           `json:"authoring"`
	Profile                  MySpaceProfile             `json:"profile"`
	RecentLearning           []MySpaceLearningHistory   `json:"recent_learning"`
	RecentLearningNextCursor *string                    `json:"recent_learning_next_cursor"`
	Summary                  MySpaceSummary             `json:"summary"`
}

// MySpaceActiveEnvironment defines model for MySpaceActiveEnvironment.
type MySpaceActiveEnvironment struct {
	Challenge          MySpaceChallenge                `json:"challenge"`
	CheckpointProgress CheckpointProgressSummary       `json:"checkpoint_progress"`
	EnvironmentId      string                          `json:"environment_id"`
	ExpiresAt          *time.Time                      `json:"expires_at,omitempty"`
	Phase              string                          `json:"phase"`
	Runtime            MySpaceActiveEnvironmentRuntime `json:"runtime"`
}

// MySpaceActiveEnvironmentRuntime defines model for MySpaceActiveEnvironment.Runtime.
type MySpaceActiveEnvironmentRuntime string

// MySpaceAuthoring defines model for MySpaceAuthoring.
type MySpaceAuthoring struct {
	Drafts    []MySpaceAuthoringDraft     `json:"drafts"`
	Published []MySpacePublishedChallenge `json:"published"`
}

// MySpaceAuthoringDraft defines model for MySpaceAuthoringDraft.
type MySpaceAuthoringDraft struct {
	SessionId string                     `json:"session_id"`
	State     MySpaceAuthoringDraftState `json:"state"`
	Title     string                     `json:"title"`
	UpdatedAt time.Time                  `json:"updated_at"`
}

// MySpaceAuthoringDraftState defines model for MySpaceAuthoringDraft.State.
type MySpaceAuthoringDraftState string

// MySpaceChallenge defines model for MySpaceChallenge.
type MySpaceChallenge struct {
	Difficulty string                  `json:"difficulty"`
	Id         string                  `json:"id"`
	Runtime    MySpaceChallengeRuntime `json:"runtime"`
	Title      string                  `json:"title"`
}

// MySpaceChallengeRuntime defines model for MySpaceChallenge.Runtime.
type MySpaceChallengeRuntime string

// MySpaceEnvironmentQuota defines model for MySpaceEnvironmentQuota.
type MySpaceEnvironmentQuota struct {
	Maximum  *int `json:"maximum"`
	Occupied int  `json:"occupied"`
}

// MySpaceLearningHistory defines model for MySpaceLearningHistory.
type MySpaceLearningHistory struct {
	Challenge             MySpaceChallenge            `json:"challenge"`
	CheckpointFirstPasses []CheckpointFirstPass       `json:"checkpoint_first_passes"`
	CompletedAt           *time.Time                  `json:"completed_at,omitempty"`
	LearningSeconds       int                         `json:"learning_seconds"`
	ReadyAt               time.Time                   `json:"ready_at"`
	State                 MySpaceLearningHistoryState `json:"state"`
}

// MySpaceLearningHistoryState defines model for MySpaceLearningHistory.State.
type MySpaceLearningHistoryState string

// MySpaceLearningPage defines model for MySpaceLearningPage.
type MySpaceLearningPage struct {
	Items      []MySpaceLearningHistory `json:"items"`
	NextCursor *string                  `json:"next_cursor,omitempty"`
}

// MySpaceProfile defines model for MySpaceProfile.
type MySpaceProfile struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
}

// MySpacePublishedChallenge defines model for MySpacePublishedChallenge.
type MySpacePublishedChallenge struct {
	AttemptedUsers int                                     `json:"attempted_users"`
	Challenge      MySpaceChallenge                        `json:"challenge"`
	CompletedUsers int                                     `json:"completed_users"`
	PassRate       *float32                                `json:"pass_rate,omitempty"`
	PublishedAt    time.Time                               `json:"published_at"`
	TaxonomyStatus MySpacePublishedChallengeTaxonomyStatus `json:"taxonomy_status"`
}

// MySpacePublishedChallengeTaxonomyStatus defines model for MySpacePublishedChallenge.TaxonomyStatus.
type MySpacePublishedChallengeTaxonomyStatus string

// MySpaceSummary defines model for MySpaceSummary.
type MySpaceSummary struct {
	AttemptedCount             int                     `json:"attempted_count"`
	AuthoringCount             int                     `json:"authoring_count"`
	CompletedCount             int                     `json:"completed_count"`
	EnvironmentQuota           MySpaceEnvironmentQuota `json:"environment_quota"`
	InProgressEnvironmentCount int                     `json:"in_progress_environment_count"`
	PublishedCount             int                     `json:"published_count"`
	TerminalLearningSeconds    int                     `json:"terminal_learning_seconds"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	TotpSecret string `json:"totp_secret"`
	TotpUrl    string `json:"totp_url"`
}

// ResetResponse defines model for ResetResponse.
type ResetResponse struct {
	ChallengeTitle string `json:"challenge_title"`
}

// StartResponse defines model for StartResponse.
type StartResponse struct {
	ChallengeTitle string `json:"challenge_title"`
}

// StopResponse defines model for StopResponse.
type StopResponse struct {
	ChallengeTitle string `json:"challenge_title"`
	Stopped        bool   `json:"stopped"`
}

// TaxonomyReference defines model for TaxonomyReference.
type TaxonomyReference struct {
	Id    string `json:"id"`
	Title string `json:"title"`
}

// TerminalTicketRequest defines model for TerminalTicketRequest.
type TerminalTicketRequest struct {
	Window string `json:"window"`
}

// TerminalTicketResponse defines model for TerminalTicketResponse.
type TerminalTicketResponse struct {
	Ticket string `json:"ticket"`
}

// TerminalWindowCloseResponse defines model for TerminalWindowCloseResponse.
type TerminalWindowCloseResponse struct {
	Closed bool `json:"closed"`
}

// VerifiedChallenge defines model for VerifiedChallenge.
type VerifiedChallenge struct {
	Checkpoints []VerifiedCheckpoint `json:"checkpoints"`
	Metadata    AuthoringMetadata    `json:"metadata"`
}

// VerifiedCheckpoint defines model for VerifiedCheckpoint.
type VerifiedCheckpoint struct {
	DependsOn   *[]string `json:"depends_on,omitempty"`
	Description string    `json:"description"`
	Hint        *string   `json:"hint,omitempty"`
	Id          string    `json:"id"`
	Title       string    `json:"title"`
}

// AuthoringSessionID defines model for AuthoringSessionID.
type AuthoringSessionID = string

// Error defines model for Error.
type Error = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetMySpaceLearningParams defines parameters for GetMySpaceLearning.
type GetMySpaceLearningParams struct {
	// Cursor Opaque cursor from a previous page
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// State Filter attempts by their current learning state
	State *GetMySpaceLearningParamsState `form:"state,omitempty" json:"state,omitempty"`

	// Runtime Filter attempts by environment runtime
	Runtime *GetMySpaceLearningParamsRuntime `form:"runtime,omitempty" json:"runtime,omitempty"`
}

// GetMySpaceLearningParamsState defines parameters for GetMySpaceLearning.
type GetMySpaceLearningParamsState string

// GetMySpaceLearningParamsRuntime defines parameters for GetMySpaceLearning.
type GetMySpaceLearningParamsRuntime string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// SendAuthoringMessageJSONRequestBody defines body for SendAuthoringMessage for application/json ContentType.
type SendAuthoringMessageJSONRequestBody = AuthoringMessageRequest

// SendChallengeAssistantMessageJSONRequestBody defines body for SendChallengeAssistantMessage for application/json ContentType.
type SendChallengeAssistantMessageJSONRequestBody = AssistantMessageRequest

// CreateTerminalTicketJSONRequestBody defines body for CreateTerminalTicket for application/json ContentType.
type CreateTerminalTicketJSONRequestBody = TerminalTicketRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with password + TOTP
	// (POST /auth/login)
	Login(c *gin.Context)
	// Register a new user
	// (POST /auth/register)
	Register(c *gin.Context)
	// Create a human-reviewed challenge authoring session
	// (POST /authoring/sessions)
	CreateAuthoringSession(c *gin.Context)
	// Resume the latest unfinished authoring session for the current user
	// (GET /authoring/sessions/current)
	GetCurrentAuthoringSession(c *gin.Context)
	// Read the current authoring revision, conversation, assets, and diff
	// (GET /authoring/sessions/{id})
	GetAuthoringSession(c *gin.Context, id AuthoringSessionID)
	// Explicitly start generation and real verification for the current intent revision
	// (POST /authoring/sessions/{id}/generate)
	ConfirmAuthoringGeneration(c *gin.Context, id AuthoringSessionID)
	// Send one natural-language instruction to the authoring agent
	// (POST /authoring/sessions/{id}/messages)
	SendAuthoringMessage(c *gin.Context, id AuthoringSessionID)
	// Explicitly publish the current verified authoring revision
	// (POST /authoring/sessions/{id}/publish)
	PublishAuthoringRevision(c *gin.Context, id AuthoringSessionID)
	// List all challenges
	// (GET /challenges)
	ListChallenges(c *gin.Context)
	// Read or create the assistant conversation for the active challenge environment
	// (GET /challenges/{id}/assistant)
	GetChallengeAssistant(c *gin.Context, id string)
	// Send a message to the active challenge assistant and receive SSE events
	// (POST /challenges/{id}/assistant/messages)
	SendChallengeAssistantMessage(c *gin.Context, id string)
	// Reconnect to a running assistant response stream
	// (GET /challenges/{id}/assistant/turns/{turnID}/events)
	StreamChallengeAssistantTurn(c *gin.Context, id string, turnID string)
	// Get challenge problem, solution, hints, and checkpoint metadata
	// (GET /challenges/{id}/content)
	GetChallengeContent(c *gin.Context, id string)
	// Read the controller-owned current challenge checkpoint snapshot
	// (GET /challenges/{id}/progress)
	GetChallengeProgress(c *gin.Context, id string)
	// Reset challenge to initial state
	// (POST /challenges/{id}/reset)
	ResetChallenge(c *gin.Context, id string)
	// Start or resume a challenge environment
	// (POST /challenges/{id}/start)
	StartChallenge(c *gin.Context, id string)
	// Stop the current challenge environment
	// (POST /challenges/{id}/stop)
	StopChallenge(c *gin.Context, id string)
	// Create a one-time ticket for a terminal WebSocket
	// (POST /challenges/{id}/terminal-ticket)
	CreateTerminalTicket(c *gin.Context, id string)
	// Close one terminal tab in the current challenge environment
	// (DELETE /challenges/{id}/terminals/{window})
	CloseTerminalWindow(c *gin.Context, id string, window string)
	// Get the authenticated user's learning space
	// (GET /me/space)
	GetMySpace(c *gin.Context)
	// Page durable learning history for the authenticated user
	// (GET /me/space/learning)
	GetMySpaceLearning(c *gin.Context, params GetMySpaceLearningParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// CreateAuthoringSession operation middleware
func (siw *ServerInterfaceWrapper) CreateAuthoringSession(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAuthoringSession(c)
}

// GetCurrentAuthoringSession operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentAuthoringSession(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCurrentAuthoringSession(c)
}

// GetAuthoringSession operation middleware
func (siw *ServerInterfaceWrapper) GetAuthoringSession(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AuthoringSessionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuthoringSession(c, id)
}

// ConfirmAuthoringGeneration operation middleware
func (siw *ServerInterfaceWrapper) ConfirmAuthoringGeneration(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AuthoringSessionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ConfirmAuthoringGeneration(c, id)
}

// SendAuthoringMessage operation middleware
func (siw *ServerInterfaceWrapper) SendAuthoringMessage(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AuthoringSessionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SendAuthoringMessage(c, id)
}

// PublishAuthoringRevision operation middleware
func (siw *ServerInterfaceWrapper) PublishAuthoringRevision(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AuthoringSessionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PublishAuthoringRevision(c, id)
}

// ListChallenges operation middleware
func (siw *ServerInterfaceWrapper) ListChallenges(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListChallenges(c)
}

// GetChallengeAssistant operation middleware
func (siw *ServerInterfaceWrapper) GetChallengeAssistant(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChallengeAssistant(c, id)
}

// SendChallengeAssistantMessage operation middleware
func (siw *ServerInterfaceWrapper) SendChallengeAssistantMessage(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SendChallengeAssistantMessage(c, id)
}

// StreamChallengeAssistantTurn operation middleware
func (siw *ServerInterfaceWrapper) StreamChallengeAssistantTurn(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "turnID" -------------
	var turnID string

	err = runtime.BindStyledParameterWithOptions("simple", "turnID", c.Param("turnID"), &turnID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter turnID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StreamChallengeAssistantTurn(c, id, turnID)
}

// GetChallengeContent operation middleware
func (siw *ServerInterfaceWrapper) GetChallengeContent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChallengeContent(c, id)
}

// GetChallengeProgress operation middleware
func (siw *ServerInterfaceWrapper) GetChallengeProgress(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChallengeProgress(c, id)
}

// ResetChallenge operation middleware
func (siw *ServerInterfaceWrapper) ResetChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResetChallenge(c, id)
}

// StartChallenge operation middleware
func (siw *ServerInterfaceWrapper) StartChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartChallenge(c, id)
}

// StopChallenge operation middleware
func (siw *ServerInterfaceWrapper) StopChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopChallenge(c, id)
}

// CreateTerminalTicket operation middleware
func (siw *ServerInterfaceWrapper) CreateTerminalTicket(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTerminalTicket(c, id)
}

// CloseTerminalWindow operation middleware
func (siw *ServerInterfaceWrapper) CloseTerminalWindow(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "window" -------------
	var window string

	err = runtime.BindStyledParameterWithOptions("simple", "window", c.Param("window"), &window, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter window: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CloseTerminalWindow(c, id, window)
}

// GetMySpace operation middleware
func (siw *ServerInterfaceWrapper) GetMySpace(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMySpace(c)
}

// GetMySpaceLearning operation middleware
func (siw *ServerInterfaceWrapper) GetMySpaceLearning(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMySpaceLearningParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", c.Request.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "runtime" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "runtime", c.Request.URL.Query(), &params.Runtime, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter runtime: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMySpaceLearning(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.POST(options.BaseURL+"/authoring/sessions", wrapper.CreateAuthoringSession)
	router.GET(options.BaseURL+"/authoring/sessions/current", wrapper.GetCurrentAuthoringSession)
	router.GET(options.BaseURL+"/authoring/sessions/:id", wrapper.GetAuthoringSession)
	router.POST(options.BaseURL+"/authoring/sessions/:id/generate", wrapper.ConfirmAuthoringGeneration)
	router.POST(options.BaseURL+"/authoring/sessions/:id/messages", wrapper.SendAuthoringMessage)
	router.POST(options.BaseURL+"/authoring/sessions/:id/publish", wrapper.PublishAuthoringRevision)
	router.GET(options.BaseURL+"/challenges", wrapper.ListChallenges)
	router.GET(options.BaseURL+"/challenges/:id/assistant", wrapper.GetChallengeAssistant)
	router.POST(options.BaseURL+"/challenges/:id/assistant/messages", wrapper.SendChallengeAssistantMessage)
	router.GET(options.BaseURL+"/challenges/:id/assistant/turns/:turnID/events", wrapper.StreamChallengeAssistantTurn)
	router.GET(options.BaseURL+"/challenges/:id/content", wrapper.GetChallengeContent)
	router.GET(options.BaseURL+"/challenges/:id/progress", wrapper.GetChallengeProgress)
	router.POST(options.BaseURL+"/challenges/:id/reset", wrapper.ResetChallenge)
	router.POST(options.BaseURL+"/challenges/:id/start", wrapper.StartChallenge)
	router.POST(options.BaseURL+"/challenges/:id/stop", wrapper.StopChallenge)
	router.POST(options.BaseURL+"/challenges/:id/terminal-ticket", wrapper.CreateTerminalTicket)
	router.DELETE(options.BaseURL+"/challenges/:id/terminals/:window", wrapper.CloseTerminalWindow)
	router.GET(options.BaseURL+"/me/space", wrapper.GetMySpace)
	router.GET(options.BaseURL+"/me/space/learning", wrapper.GetMySpaceLearning)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Dxbb9s6mn+F0A6wD6vU6TmDBU7eOml7tgcdNJtkpg9F1qClzzYnEqmSlFNvkf++4E2iJFKWnDjbzrzM",
	"9MS8fPcbv0/fk4yVFaNApUguvicV5rgECVz/15tabhkndHMDQhBGP7xVfyU0uUgqLLdJmlBcQnKRkDxJ",
	"Ew5fa8IhTy4kryFNRLaFEqsdcl+pVUKqs5LHx0e1WFSMCtD3vOOccfWPjFEJVKp/4qoqSIYlYXTxD8Go",
	"+lt74p84rJOL5N8WLfgL86tY6NOu7fnmthxExkmlDksu7HXq73aLxlUIIiSm8pLRHXCBzeLvScVZBVwS",
	"AyrOJNnBUtacHoKjOfFWLX5Mk2yLiwLoBpYkD5AlTSJ/LkEIvDH3EwmlmHzzX81OdYg9FXOO94nhgGPX",
	"F8O/DnjerXfNZrb6B2RSndbc8G5HcqAZDCl1T2gYnQKvoAiJRRcmvd+tHoXBYTkAwROnARQZBywhX+Lw",
	"z+DhNY/mDUUGRI8ymLNCXwS0LhXqtQCepAl2R3roR4hlFFAdkzZYd3CcQsBr+FqDkDPpWHMOVC4fCM3Z",
	"Q3AJq4Da37syPFg5KqQeXt07ezeMonprFff5BMXZrv9fESpbHZhrGYQx7jGjJCSWtfDFk9eUqh9T7TwK",
	"kKCkb41JAXlAVNOkrvI4CUOS7IHUABAR7M7pQdY7J/aGS7LGWUC+c8Ihk4zvgwTYAAWOJeNLXsepVK9K",
	"MkLHHpbd5akHQeC+cayEgJkqq333QRCth3cHjQJxucU0ZIBzsl6TrC7kfknKytJ+AE/UU3DYEWHdsP2R",
	"UAkb4IbkZYmDPAt7Erc+DYDl3XUAUcjuK0ZogOQxzcT8PmcPNMwKJoiMYiiJNI5hgsqYtd513uGjKL0n",
	"Bbwl63WYe08XIH3KKARx/63Fakbc05PHgPmcbunXjJfqX4myLmeSlIq6U0O2mEffGPsl9kJCmSgfAadz",
	"7z36HuHeIx74wG0S51jigDz5UXiAaK1a+qQDLPY6HM1JrUi2xTzsZXhNNZe8vQpgTKim/S4raiGBB/dO",
	"1DSnZB6k3eSihWKURlcFDkUhjXE5SuQbyxQQ+9JjyqTjGi6q+G0HfEfg4TB9mmu8TWkHr1Gy2DQzkHV5",
	"rnsS+I2vf9RhNBxDUeNZA8TEboVOA5cmJRwIePJ5C3ILHMktoLzmeFUAaraiN8oUoOuaIiJQBTRXf2Qc",
	"2eDqFfq8JQUgnUrrI6oC67UrUCtt0IMqTnZYQrFHmOb2eKQgYlQgzAHVFO8wKdTtr1oDtmKsAEyd1s0n",
	"TuM1AvSZFDDF/tyYoklgaEVqti3HA4b5eXTfQwWQrepVQcR2eTC5V2Fsxzi95XjdrTakyQeNxzVYzfnd",
	"UFIJI83/Dpys9ybw1v+25ZEPdM2xkLzOZM3hvQnD0+TNAyZqp1kKeXPotSbS4Mgrg0jnPybF89Mc5c6D",
	"eDLdfTTbQyA/dIDD+dIxpdm8X0os7mM8UoRZFTAqR8F8RfM2ZhmG4hm4qUPVRg88oW0M2ZSQ6u89ag/i",
	"qnFZ9bLJYfC3xQIi4XrFuDyKuddmq9KvKHv6vtgudBC1UE+mzAch6mDZKIeZZBkESvlRAF03FOz5Pyoe",
	"gC8rJQE+aTwzvqpJkY+u8Nzw+LoCi06+33hfJZa+rQkaB6KIeoSNHTImYG0n53wdcqQ9AgZpEWJSYz/G",
	"8r4clPsWS6NpU4tb6cFweEsieUpEaY/JFn0YxgnQ5ghPD1pDZA0QaOsOxXmuE1lcXHXujpG4hT9Cqoqz",
	"VQFl2E+zoo7yROJvjLJyPxnDW7fhSAY5SD24HGG6gbUH2ygj31HJ9zf3pCgmVzAscNP565C+hjXwWCHz",
	"GGo0kIyi+JEEs1z38xFyemPNzsESdXvHKISfapmxEiZzoOKkZ/Y8e32cWJkDR6G84mzDwfiCgNLPoaOT",
	"02sQdSEn0FGfPwrdTesKQk90YVqduAQxzr4la9k+W30qjxnTaO3Y5wlv5cL6WaH7UworghW7WKAh8eaF",
	"bIpbOUtH9NIW+17VRwM/ZG2/HNSh+Kg833qupSvQoEz2UiibfYTt8gx+gGIW7iPOdTYslBM/g7wHUjDf",
	"DT+v5PTEwEvKomxuCJd2+RPmsdPJ94QLeYWjNlUvimVla7XZhquzFHhy1NyFYXhje9Q4mn3TM0C2zT9K",
	"QkmpjMp5GnoBYRIXh5YN3h1skG82j0NqHVIgqJeYFOJJfKB1oeturiFmsrsYSc4ms9Jkxo4UY2zr9ssM",
	"rU/kgbt3n1kWOv8j2xAafXxQID4wHklpmKyW0XS8FsBNA9Ih4JqVaXuff/oI2DGyRC5Wp94DHVaD//h8",
	"i3CWgRDIrEjDCE2rfdgT3AbbiBVC46/7mwqH+nNsJxPQHeGMljAngbOHvtFHvGtPGK2WTz20WW+injUp",
	"YOLWK7taUysDKpcFYE7t3XMw+2j3/RcR+lU+gFfvhiWFb3KZ1VwYbTmo/J4mTwCoCeL6xs6i7D9vhzg7",
	"pMg4Bj7fRsRqKAHxvGsipp2areeQniUA9mgS87LwrVIp5pMM+0iN9OhYum9vu5h47XudmNXVRkOEHOOr",
	"r7Q9z8jx+ghT4Q7Urx4jDynG8c05unmr6EjOaIBncfAvnUIMA/uAIhMaqP5JHn7i+dX8J6F+R5Tf8uVS",
	"MPeucqDFa2A5RhqR5lRUX6CjoFveCqWaIwh7dve/axZquSjxNxM2dyPoiAHzAm+WZXVFDofoPXSabWlz",
	"9Qj8fS97Mt/hRezHVK3arC3YUWR7IJ/kMRonLCBjNBeHUyMOON/PSwP7hqh5n/T7OIVkVQWmoV+AyvmM",
	"R8wP+6SOC3LgBXBrFTvGowlCcxVsGWs4+8zR3rzorq/kGpYRnK7aMLenAM/XkjYtU2qTiYP9ZXH3O8w1",
	"pISyUmepjGWCcD9N8RuNnHibErolt8rREHldMC2+EV7TulzZ7UdVVd1zzXLYYF1iq4HqHy5Wl9z661XB",
	"svu56tiBcXh5OmDRkIwjMhCvxTenZqw22cE4K9oOiokbWignbvAD56/Oa04QsYGz1W1HTTTtp1tTQWmZ",
	"MnGDBF4SiovlXHcx6E/oEi0dMOoQbmOwDLk4RDXEh5CAXcOGqBhrUv2oJPQj0I3cJhf/mY7Xi7ylv6RH",
	"VI/GYY0VjXTFSUDGQcbrXTUvplSA2pO8fWGwBMg4TG0z0MSQtb8hdOeNxPzl72TVU65sQ59A5bWfrTRB",
	"0hTIhi8QUx9+52cRwfutqt6S7F6JQkSV2hGuSpkDTpOL5H++4LP/vVP/c37229nd9/P019ePfzqYzdmj",
	"pgAT1RX9+5SebL1u7KrPGprLggkYERD18xTe24WhC4d9h8/SL9Mee6Ie73gb96He7QBo/0INUnp6Lqs5",
	"kfsbRV2D7wowB67I3P7XexcT/vH5NrGDx1rI9K+tPm2lrMzMMqFrNnxGuLl+t3gLu0+VQMq56xZ7VHGV",
	"yWW6R1yq6LNB4CL5Cwd8vybf0JurD4lugjWvqsnrV+evzt14Jq5IcpH8+ur81a+Jme/RmCyUI18UbENM",
	"FykzZkMx11Sg8uTCPJTY5hwQ8i8s3z/bLHfn7eixyykVjfcnyX85P3/uu+Nz5HoBErV+1VnXRYo4yJpT",
	"gf74fGtfeR7T5M/nr2NXNbAvvJl0F0vb8x+I3CIXd6D/QLefbq/cw7TK4ZWY3amNhlncBiFxfrkw5UQs",
	"60dsk7j2+gTXxxn3NwEcOUJBbph0fhyT3H0IIwoPyA56Rbijze7CljpFnEWXOvMezMWcUNgHdwXI1qxB",
	"FgNkKwQdQ5hcfOmawC93j3c+xQxyCKNtXWJ6xnV5GnLURFLelIxoMPcpap+lImRd2PFwhfIGAtT9HeSl",
	"WfKjUdiChWq6JlSnSwFaaGn98yxpncqaaxB1CXrcqMASxDgkaM3MdFPmwB4K/wFWfSf54xifAgzyP1Hy",
	"JUyDdski8AkThfIPweUXZi3OO8xqb3ftTinKvEepFJl5k1RPlumRk9msXdhRMBgxdYyuCS8burmXr38S",
	"Xv/uZuH0qJ+ipD8IhYTKk+ca0HffFMREFnuzH20amukbOOCie01fUc10Eer3uc1grD9LF2bsDdB8MED3",
	"bCx9/rglNi79wlHnFKH6mx3+fFEDoviJGAVEsaw5Ls4KTDc13gAi1DxCK0mTTAtaC5kbeZ8rYLZgGJcv",
	"++7Q0Ou6Feaf32y4tLpRUdR2KhxrK+wJHUPgBioD3mCEZ91RiqDv/kiEvGyXnZCc3bGPkLtt4srCrOjk",
	"WERIhIsCZT6wDnF/nqOHuZHS9hNNY8Gm29R8fWcoo0//qNpJRTb4cbTQp9Xaov6ZyFilJMvt7UQXcy2V",
	"Wv3b6QIjxm0uY6xXEOTGi5pncy9f8Z4yfK1pP981LjsTnelQjKJe9Zmk6QRONvLJsaOcrIRvcqG/oHIm",
	"JAdcduEIfHWwV0sDvgN+JnQ03LDcvIimSDJWpCiHQmIVGJsHMxMM615npG8Wc4sHP4rYa3eOkRW9xm/3",
	"Rbuli4ksM1C/39y8c+gfI++6SLb4rv7vw9vHhT0pZkFvNG+H0q8/5XYC0U+Dhxhgn9ki/0AS/GOY4oxR",
	"CplU4ojdp1A8zNzpyFJruvB5RD/opi+bLyz9VE56AP9oLOSuPGHG8DtIz5LYSeYUuUHmFOk5ZiOQ7TsT",
	"8l6fJsdhfnP4Qf42c60/K4MbBEaKSx5BuZ5xEj9YyKXTEEYlZ0UB/Iw9UMibvKQVGw8PQXEltsyPsToz",
	"DmHRMF2MI68hwhONn00kur0dowpv6HDa4nFH4SVDhBJJcIFcu+cMtunK1khArH7+adnWbY8Zz6OQ7qQ9",
	"aWVHFxEZ14aiBIQPpjaT+MeqMfax6ifmntdoNKpzrk3opMxjVaek8wy8c619Z20Pztg7Zbej5yfKRsN9",
	"US9c8I30Q4Wi/S3j8qwgO9CFWN1ZjByvkOXVCUWtebhtL9d36sIIbiH5DKsbZkXhCKkTi++mfezRtL+o",
	"rCUgegUT0G3werlksPnwePygI1ro7l5AykKtcAFRc8uRwRTZnrdTCpe6Qb8vtBKNV4jQpxq3EhbCTUDH",
	"UgM3JH1CBrgrQn1EtoEabc38SerKMD42qfeBT/3i0w61zm0wmpO/ucccoFLhDbl+5P93gVzXNxKWco4F",
	"dligQ/uFP4d9gAkf2wHlnjZ3qfapwl9rLRmCcbTmrEQYVRx2hNUCVaYuqnX3aw16LtoqbzPhfFjrezsL",
	"UhLZ2ZjDGuvvR/xy3k68Xbw+V//l2vFfh9rx+9i8J4VuIjJt+AKt9or0hDeS39LbxtIhAN1vLYCjo15A",
	"88gcyQTwwA9Rm8HFEFTtr0O4pg4/351eNTuDZQE1/URBixVi65Yb23Zk7FRqqOBpPiDcv7h9lBgoaUgn",
	"9b18F9aojyzDBcphl6SJHkLQ3agXi0WhftgyIS9+O//tfIErkjzePf5fAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
