// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// ChallengeDraft defines model for ChallengeDraft.
type ChallengeDraft struct {
	AcceptanceCriteria string   `json:"acceptance_criteria"`
	Description        string   `json:"description"`
	Difficulty         string   `json:"difficulty"`
	DifficultyReason   string   `json:"difficulty_reason"`
	EnvironmentShape   string   `json:"environment_shape"`
	FaultMechanism     string   `json:"fault_mechanism"`
	Goal               string   `json:"goal"`
	Notes              *string  `json:"notes,omitempty"`
	Symptoms           string   `json:"symptoms"`
	Tags               []string `json:"tags"`
	Title              string   `json:"title"`
}

// ChallengeList defines model for ChallengeList.
type ChallengeList struct {
	Challenges *[]ChallengeSummary `json:"challenges,omitempty"`
}

// ChallengeSummary defines model for ChallengeSummary.
type ChallengeSummary struct {
	Active      *bool     `json:"active,omitempty"`
	Description *string   `json:"description,omitempty"`
	Difficulty  *string   `json:"difficulty,omitempty"`
	Id          *string   `json:"id,omitempty"`
	Runtime     *string   `json:"runtime,omitempty"`
	Solved      *bool     `json:"solved,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       *string   `json:"title,omitempty"`
	Type        *string   `json:"type,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// GenerateDraftRequest defines model for GenerateDraftRequest.
type GenerateDraftRequest struct {
	Topic string `json:"topic"`
}

// GenerateDraftResponse defines model for GenerateDraftResponse.
type GenerateDraftResponse struct {
	Draft    *ChallengeDraft `json:"draft,omitempty"`
	Reason   *string         `json:"reason,omitempty"`
	Status   *string         `json:"status,omitempty"`
	Verdict  *string         `json:"verdict,omitempty"`
	Warnings *[]string       `json:"warnings,omitempty"`
}

// GenerationJobCreateRequest defines model for GenerationJobCreateRequest.
type GenerationJobCreateRequest struct {
	Draft ChallengeDraft `json:"draft"`
}

// GenerationJobResponse defines model for GenerationJobResponse.
type GenerationJobResponse struct {
	ChallengeId *string    `json:"challenge_id,omitempty"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	JobId       *string    `json:"job_id,omitempty"`
	Message     *string    `json:"message,omitempty"`
	StartedAt   *time.Time `json:"started_at,omitempty"`
	Status      *string    `json:"status,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	TotpCode string `json:"totp_code"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Name *string `json:"name,omitempty"`

	// Token JWT access token
	Token  *string `json:"token,omitempty"`
	UserId *string `json:"user_id,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	TotpSecret *string `json:"totp_secret,omitempty"`
	TotpUrl    *string `json:"totp_url,omitempty"`
}

// ResetResponse defines model for ResetResponse.
type ResetResponse struct {
	ChallengeTitle *string `json:"challenge_title,omitempty"`
}

// StartResponse defines model for StartResponse.
type StartResponse struct {
	ChallengeTitle *string `json:"challenge_title,omitempty"`
}

// StopResponse defines model for StopResponse.
type StopResponse struct {
	ChallengeTitle *string `json:"challenge_title,omitempty"`
	Stopped        *bool   `json:"stopped,omitempty"`
}

// SubmitResponse defines model for SubmitResponse.
type SubmitResponse struct {
	ExitCode *int    `json:"exit_code,omitempty"`
	Output   *string `json:"output,omitempty"`
	Passed   *bool   `json:"passed,omitempty"`
}

// VerifyIssue defines model for VerifyIssue.
type VerifyIssue struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// VerifyReport defines model for VerifyReport.
type VerifyReport struct {
	AnswerPassed *bool          `json:"answer_passed,omitempty"`
	BuildPassed  *bool          `json:"build_passed,omitempty"`
	Issues       *[]VerifyIssue `json:"issues,omitempty"`
	Summary      *string        `json:"summary,omitempty"`
	VerifyPassed *bool          `json:"verify_passed,omitempty"`
}

// VerifySubmissionResponse defines model for VerifySubmissionResponse.
type VerifySubmissionResponse struct {
	Status       *string `json:"status,omitempty"`
	SubmissionId *string `json:"submission_id,omitempty"`
	VerifyTaskId *string `json:"verify_task_id,omitempty"`
}

// VerifyTaskResponse defines model for VerifyTaskResponse.
type VerifyTaskResponse struct {
	CompletedAt  *time.Time    `json:"completed_at,omitempty"`
	Message      *string       `json:"message,omitempty"`
	Report       *VerifyReport `json:"report,omitempty"`
	StartedAt    *time.Time    `json:"started_at,omitempty"`
	Status       *string       `json:"status,omitempty"`
	SubmissionId *string       `json:"submission_id,omitempty"`
	VerifyTaskId *string       `json:"verify_task_id,omitempty"`
}

// Error defines model for Error.
type Error = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// CreateVerifySubmissionMultipartBody defines parameters for CreateVerifySubmission.
type CreateVerifySubmissionMultipartBody struct {
	Artifact openapi_types.File `json:"artifact"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateGenerationJobJSONRequestBody defines body for CreateGenerationJob for application/json ContentType.
type CreateGenerationJobJSONRequestBody = GenerationJobCreateRequest

// ReviewGenerationDraftJSONRequestBody defines body for ReviewGenerationDraft for application/json ContentType.
type ReviewGenerationDraftJSONRequestBody = GenerateDraftRequest

// CreateVerifySubmissionMultipartRequestBody defines body for CreateVerifySubmission for multipart/form-data ContentType.
type CreateVerifySubmissionMultipartRequestBody CreateVerifySubmissionMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with password + TOTP
	// (POST /auth/login)
	Login(c *gin.Context)
	// Register a new user
	// (POST /auth/register)
	Register(c *gin.Context)
	// List all challenges
	// (GET /challenges)
	ListChallenges(c *gin.Context)
	// Reset challenge to initial state
	// (POST /challenges/{id}/reset)
	ResetChallenge(c *gin.Context, id string)
	// Start or resume a challenge environment
	// (POST /challenges/{id}/start)
	StartChallenge(c *gin.Context, id string)
	// Stop the current challenge environment
	// (POST /challenges/{id}/stop)
	StopChallenge(c *gin.Context, id string)
	// Submit solution for verification
	// (POST /challenges/{id}/submit)
	SubmitChallenge(c *gin.Context, id string)
	// Start generation for a reviewed challenge draft
	// (POST /generate)
	CreateGenerationJob(c *gin.Context)
	// Review and expand a challenge idea into a structured draft
	// (POST /generate/draft)
	ReviewGenerationDraft(c *gin.Context)
	// Get generation job status
	// (GET /generate/jobs/{id})
	GetGenerationJob(c *gin.Context, id string)
	// Upload a challenge artifact for platform verification
	// (POST /verify/submissions)
	CreateVerifySubmission(c *gin.Context)
	// Get verification task status
	// (GET /verify/tasks/{id})
	GetVerifyTask(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// ListChallenges operation middleware
func (siw *ServerInterfaceWrapper) ListChallenges(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListChallenges(c)
}

// ResetChallenge operation middleware
func (siw *ServerInterfaceWrapper) ResetChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResetChallenge(c, id)
}

// StartChallenge operation middleware
func (siw *ServerInterfaceWrapper) StartChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartChallenge(c, id)
}

// StopChallenge operation middleware
func (siw *ServerInterfaceWrapper) StopChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopChallenge(c, id)
}

// SubmitChallenge operation middleware
func (siw *ServerInterfaceWrapper) SubmitChallenge(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubmitChallenge(c, id)
}

// CreateGenerationJob operation middleware
func (siw *ServerInterfaceWrapper) CreateGenerationJob(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGenerationJob(c)
}

// ReviewGenerationDraft operation middleware
func (siw *ServerInterfaceWrapper) ReviewGenerationDraft(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReviewGenerationDraft(c)
}

// GetGenerationJob operation middleware
func (siw *ServerInterfaceWrapper) GetGenerationJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGenerationJob(c, id)
}

// CreateVerifySubmission operation middleware
func (siw *ServerInterfaceWrapper) CreateVerifySubmission(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateVerifySubmission(c)
}

// GetVerifyTask operation middleware
func (siw *ServerInterfaceWrapper) GetVerifyTask(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVerifyTask(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.GET(options.BaseURL+"/challenges", wrapper.ListChallenges)
	router.POST(options.BaseURL+"/challenges/:id/reset", wrapper.ResetChallenge)
	router.POST(options.BaseURL+"/challenges/:id/start", wrapper.StartChallenge)
	router.POST(options.BaseURL+"/challenges/:id/stop", wrapper.StopChallenge)
	router.POST(options.BaseURL+"/challenges/:id/submit", wrapper.SubmitChallenge)
	router.POST(options.BaseURL+"/generate", wrapper.CreateGenerationJob)
	router.POST(options.BaseURL+"/generate/draft", wrapper.ReviewGenerationDraft)
	router.GET(options.BaseURL+"/generate/jobs/:id", wrapper.GetGenerationJob)
	router.POST(options.BaseURL+"/verify/submissions", wrapper.CreateVerifySubmission)
	router.GET(options.BaseURL+"/verify/tasks/:id", wrapper.GetVerifyTask)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FlLb9swEv4rBHdv68buAwvUt762aFGgRZK2h8AwaGlsM5FIdjhyahT+7wtSkiXZpKJk4y5yiiJSw5nv",
	"mxfHf3iic6MVKLJ8+ocjWKOVBf/PB0SN7iHRikCRexTGZDIRJLUaX1ut3DubrCEX7umfCEs+5f8YN1LH",
	"5aode2nnlXy+2+1GPAWboDROGJ9Wx7n31SdO4ru1yDJQK3iPYuk1MKgNIMlSR5EkYEioBOYJSgKUXhHa",
	"GuBTbgmlWvHDo0LrcrmUSZHR9o7lOYKwESGgNhK1ykHR3K6FWw3sWooio3kOyVooafPgnpUWWXBBaSoN",
	"P1qx29yQzsOLJFZ+QRLEdpQvBKLY+v8lZSH9dyOO8KuQCCmfXlXbOvhVp3Uxr0xqqXkMRAjAUZDhECGz",
	"vQ16cQ0JOSP23vNF2oDzJPVyF5s+L95LvCjyXOD2GLpdnx71VwE/Jrlp473QOgOhHsF3ZRr2F51tIA2f",
	"+HjuUu8M+dERTN0UcYQR1Pmo3yXLbSF3+AgKUFCZS87hVwEhryBtZDLA8/22AcfEzEnrjDbI38r853WI",
	"5h9LgoowXxvAVCYUXLsVqKS6H+O7uN1Sq8968Q5BEERBfpDxBwyUMmZ3aRJnYB//80iMOJ0yIEjnwiu7",
	"1Ji7J54Kgmckc5egjr661ouYwBysFSuIsYf3PSrKeIifL3olVZQRI6y91RjWmzSZeaLTsOaFBVQiH1Au",
	"9jtHzXlt6bO42jESIwc7qTfg46TbZnz+eclcTbGWlTtGYYPCFIZwPYeVtAQ4CNpcqi+gVrTm03+P+qFs",
	"bX0xegCws15dY3h6MiwkCBR3hQKzweBYoCEh2NNwHAm9cKHy+EK1+V9kumjUxoRravDAYpHLHjPgt6TD",
	"oJOKYAXoPtcFmSLMkXOB4Xr8AJTL7Sdri5DdsaCPp7L4GedgNIa6eGVvAedxtUd8Ucgs7d0hnQHDO7m2",
	"1YGGxjadWqiYyuV2/hCUPefWSt2T0XrKuN1/HqswlW4k7M3wDFbqdinsTU8APKgW9hU83HvD3TxVnvPY",
	"ZfJEiDq5kBQoaXvhzCgRXIBAwDeFS+j1f/+p9f/885JXN1/vSn61sWVNZMpLs1RLfVzVLs4/jN/D5qux",
	"zKUI3Ei4ZQbdtSIBZjJBDim+b9T5WwRxs5S/2Ztvn7g30paSnp9NziY+vxhQwkg+5S/PJmcvfWWhtbdk",
	"LApajzNXmL2j6LLqOXfxXdenlE/Lus3LMgWW3up0+2jDhE4rs+sWQ8IC/IvWKOPFZPLYZ8cHGX4Ds4Vv",
	"MpZFNmIIVKCyzPUeZdOxG/FXk+exo/a6j1tDkTohVfJvJa1ZXevZv9jl18tv9d17esUdQ3zmPizJwqrw",
	"x/mqW4MTUXbYJQ1i7fkJjo8T990CshooSEuSJg8jqT6PCabglrn+LMxOdwixglAkSUvvmm0n9O3uwCQA",
	"0X4Dy8odTabj06tujrua7WYdv5WWmMgylrRtqSFpvTwEZvxHpjuHdwlOzH0tNCj5bIUiBwK0XjOXqnwG",
	"46PqzsBlyg9dcNQC6jDNz04IfLdN7gW+xMH75qt7+eZQnrwuDUmMNJNKkhQZc4UUWqS1BnYx2ny9jtPm",
	"W/knS1v3IhIaajcAMQSRbk9JnNeGaZfDbJEDEy0SW0zdlz9t+ujT5gmz17rx9cZcfbM7KXnaMFoDSwpE",
	"5y6PwZ2/Yfaw59efLn/dC3SAwea65WMiO2neLNVhVmeFO54tNTJ/eais6+duVU2N42yVI9XObPNEvVrP",
	"JPcvN9vhSW6A6WYju9YLlnil04fkz1UjyTEoGIK7TUHaishy9Nzq51bO0i6R4/2MO9awOLGN3u8rmSck",
	"tPvLx/+HyoOfRQJU+g0V6vuwvV8D4z8VKmXw27g/7UooUxDukqyZYJawSKhASIdReq0XZWqN9uofgQ4j",
	"9Enl1IcGXDViOWF6/Qid2GwdGiatnNuMmwGPvSu1Ho7oeoMxLzKSRiCNlxrzZ6kg0UX5YMSJJJci6Q6t",
	"FlI52+4a7u+/PZ7o/90Qjs4wA/7xo1X5GAl70+Tk+1+rh/rId5Np0Q33GjyfzOtBWKwulz7TdSCn+91B",
	"34xQn1rEB4a/g+j8OxG/iZ0bIs0Lx02N++FYLhEZS2HDR9z/fuWHqtPxOHMLa21p+nryejIWRvLdbPff",
	"AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
