// Package agentruntime defines the durable, provider-neutral execution state
// shared by authoring, the learning assistant, generator, and taxonomy jobs.
package agentruntime

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"time"
)

var (
	ErrNotFound  = errors.New("agent runtime record not found")
	ErrRunActive = errors.New("agent session already has an active run")
	ErrLeaseLost = errors.New("agent run lease was lost")
)

type SessionStatus string

const (
	SessionActive SessionStatus = "active"
	SessionClosed SessionStatus = "closed"
)

type RunStatus string

const (
	RunPending   RunStatus = "pending"
	RunRunning   RunStatus = "running"
	RunSucceeded RunStatus = "succeeded"
	RunFailed    RunStatus = "failed"
	RunCancelled RunStatus = "cancelled"
)

type Session struct {
	ID        string
	Purpose   string
	OwnerKind string
	OwnerRef  string
	UserRef   string
	Status    SessionStatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Message struct {
	ID        string
	SessionID string
	Sequence  int64
	Role      string
	Content   string
	CreatedAt time.Time
}

type Run struct {
	ID             string
	SessionID      string
	Purpose        string
	OwnerKind      string
	OwnerRef       string
	InputRevision  string
	Status         RunStatus
	Model          string
	PromptVersion  string
	Attempt        int
	NextAttemptAt  time.Time
	LeaseOwner     string
	LeaseExpiresAt *time.Time
	DeadlineAt     time.Time
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    *time.Time
}

// Claim is the attempt-scoped authority a Worker must present for every
// mutation. Lease owner is generated by the Worker and never reused between
// claims of a run.
type Claim struct {
	Run        Run
	LeaseOwner string
}

func (c Claim) Valid() bool {
	return c.Run.ID != "" && c.Run.Attempt > 0 && strings.TrimSpace(c.LeaseOwner) != ""
}

type CreateRun struct {
	ID            string
	SessionID     string
	Purpose       string
	OwnerKind     string
	OwnerRef      string
	InputRevision string
	Model         string
	PromptVersion string
	DeadlineAt    time.Time
}

type Repository interface {
	CreateSession(context.Context, Session) (*Session, error)
	FindOrCreateSession(context.Context, Session) (*Session, error)
	FindSession(context.Context, string, string, string, string) (*Session, error)
	GetSession(context.Context, string) (*Session, error)
	ListMessages(context.Context, string) ([]Message, error)
	CreateMessageAndRun(context.Context, Message, CreateRun) (*Run, error)
	CreateRun(context.Context, CreateRun) (*Run, error)
	GetRun(context.Context, string) (*Run, error)
	GetActiveRunForSession(context.Context, string) (*Run, error)
	ClaimNext(context.Context, string, time.Duration, time.Time) (*Claim, error)
	RenewLease(context.Context, Claim, time.Duration, time.Time) error
	Requeue(context.Context, Claim, time.Time, string, time.Time) error
	CompleteWithMessage(context.Context, Claim, Message, time.Time) error
	Fail(context.Context, Claim, string, time.Time) error
	Cancel(context.Context, string, time.Time) error
	CancelRunsForOwner(context.Context, string, string, string, time.Time) (int64, error)
	ValidateLease(context.Context, Claim, time.Time) error
}

func NewID(prefix string) string {
	var raw [16]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return fmt.Sprintf("%s-%d", prefix, time.Now().UnixNano())
	}
	return prefix + "-" + hex.EncodeToString(raw[:])
}

func ValidateCreateRun(run CreateRun) error {
	if strings.TrimSpace(run.ID) == "" || strings.TrimSpace(run.Purpose) == "" || strings.TrimSpace(run.OwnerKind) == "" || strings.TrimSpace(run.OwnerRef) == "" {
		return errors.New("agent run requires id, purpose, owner kind, and owner ref")
	}
	if strings.TrimSpace(run.Model) == "" || strings.TrimSpace(run.PromptVersion) == "" {
		return errors.New("agent run requires model and prompt version")
	}
	if run.DeadlineAt.IsZero() {
		return errors.New("agent run deadline is required")
	}
	return nil
}
