// Package agentruntime defines the durable, provider-neutral execution state
// shared by authoring, the learning assistant, generator, and taxonomy workflow.
package agentruntime

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
)

var (
	ErrNotFound  = errors.New("agent runtime record not found")
	ErrRunActive = errors.New("agent session already has an active run")
	ErrLeaseLost = errors.New("agent run lease was lost")
)

const ExecutionDeadline = time.Hour

type SessionStatus string

const (
	SessionActive SessionStatus = "active"
	SessionClosed SessionStatus = "closed"
)

type RunStatus string

const (
	RunPending   RunStatus = "pending"
	RunRunning   RunStatus = "running"
	RunSucceeded RunStatus = "succeeded"
	RunFailed    RunStatus = "failed"
	RunCancelled RunStatus = "cancelled"
)

type Session struct {
	ID        string        `json:"id"`
	Purpose   string        `json:"purpose"`
	OwnerKind string        `json:"owner_kind"`
	OwnerRef  string        `json:"owner_ref"`
	UserRef   string        `json:"user_ref,omitempty"`
	Status    SessionStatus `json:"status"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type Message struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Sequence  int64  `json:"sequence"`
	Role      string `json:"role"`
	Content   string `json:"content"`
	// Metadata holds small domain-visible annotations such as the Assistant's
	// evidence labels. It never holds tool output, prompts, or model reasoning.
	Metadata  json.RawMessage `json:"metadata,omitempty"`
	CreatedAt time.Time       `json:"created_at"`
}

type Run struct {
	ID            string `json:"id"`
	SessionID     string `json:"session_id,omitempty"`
	Purpose       string `json:"purpose"`
	OwnerKind     string `json:"owner_kind"`
	OwnerRef      string `json:"owner_ref"`
	InputRevision string `json:"input_revision,omitempty"`
	// Input is immutable, run-scoped context needed to reconstruct an attempt.
	// It is deliberately not conversation history or a provider checkpoint.
	Input         json.RawMessage `json:"input"`
	Status        RunStatus       `json:"status"`
	Model         string          `json:"model"`
	PromptVersion string          `json:"prompt_version"`
	// DeadlineAt is assigned when the Run's WorkItem is first claimed. Queued
	// Runs intentionally have no execution deadline yet.
	DeadlineAt  *time.Time `json:"deadline_at,omitempty"`
	LastError   string     `json:"last_error,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
}

// Claim is the attempt-scoped authority a Worker must present for every
// mutation. Lease owner is generated by the Worker and never reused between
// claims of a run.
type Claim struct {
	Run        Run    `json:"run"`
	WorkItemID string `json:"work_item_id"`
	Attempt    int    `json:"attempt"`
	LeaseOwner string `json:"lease_owner"`
}

func (c Claim) Valid() bool {
	return c.Run.ID != "" && strings.TrimSpace(c.WorkItemID) != "" && c.Attempt > 0 && strings.TrimSpace(c.LeaseOwner) != ""
}

// LeaseCredential is the complete attempt fence carried by every Worker
// request after a claim. The Server never infers a WorkItem from a Run ID.
type LeaseCredential struct {
	WorkItemID string `json:"work_item_id"`
	Attempt    int    `json:"attempt"`
	LeaseOwner string `json:"lease_owner"`
}

func (c Claim) Credential() LeaseCredential {
	return LeaseCredential{WorkItemID: c.WorkItemID, Attempt: c.Attempt, LeaseOwner: c.LeaseOwner}
}

func (c LeaseCredential) Valid() bool {
	return strings.TrimSpace(c.WorkItemID) != "" && c.Attempt > 0 && strings.TrimSpace(c.LeaseOwner) != ""
}

type CreateRun struct {
	ID               string
	SessionID        string
	Purpose          string
	OwnerKind        string
	OwnerRef         string
	InputRevision    string
	Input            json.RawMessage
	Model            string
	PromptVersion    string
	ExecutionTimeout time.Duration
}

type Repository interface {
	CreateSession(context.Context, Session) (*Session, error)
	FindOrCreateSession(context.Context, Session) (*Session, error)
	FindSession(context.Context, string, string, string, string) (*Session, error)
	GetSession(context.Context, string) (*Session, error)
	ListMessages(context.Context, string) ([]Message, error)
	CreateMessageAndRun(context.Context, Message, CreateRun) (*Run, error)
	CreateRun(context.Context, CreateRun) (*Run, error)
	GetRun(context.Context, string) (*Run, error)
	GetActiveRunForSession(context.Context, string) (*Run, error)
	ListActiveRunsForPurpose(context.Context, string) ([]Run, error)
	ClaimNext(context.Context, string, time.Duration, time.Time) (*Claim, error)
	RenewLease(context.Context, Claim, time.Duration, time.Time) error
	Requeue(context.Context, Claim, time.Time, string, time.Time) error
	CompleteWithMessage(context.Context, Claim, Message, time.Time) error
	Fail(context.Context, Claim, string, time.Time) error
	Cancel(context.Context, string, time.Time) error
	CancelRunsForOwner(context.Context, string, string, string, time.Time) (int64, error)
	ValidateLease(context.Context, Claim, time.Time) error
}

func NewID(prefix string) string {
	var raw [16]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return fmt.Sprintf("%s-%d", prefix, time.Now().UnixNano())
	}
	return prefix + "-" + hex.EncodeToString(raw[:])
}

func ValidateCreateRun(run CreateRun) error {
	if strings.TrimSpace(run.ID) == "" || strings.TrimSpace(run.Purpose) == "" || strings.TrimSpace(run.OwnerKind) == "" || strings.TrimSpace(run.OwnerRef) == "" {
		return errors.New("agent run requires id, purpose, owner kind, and owner ref")
	}
	if strings.TrimSpace(run.Model) == "" || strings.TrimSpace(run.PromptVersion) == "" {
		return errors.New("agent run requires model and prompt version")
	}
	if run.ExecutionTimeout <= 0 {
		return errors.New("agent run execution timeout is required")
	}
	if len(run.Input) > 0 && !json.Valid(run.Input) {
		return errors.New("agent run input must be valid JSON")
	}
	return nil
}
