// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: breakfix.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BreakfixClient is the client API for Breakfix service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BreakfixClient interface {
	// Auth
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Challenges
	ListChallenges(ctx context.Context, in *ListChallengesRequest, opts ...grpc.CallOption) (*ListChallengesResponse, error)
	// Instance lifecycle (keyed by user + challenge_id)
	StartChallenge(ctx context.Context, in *StartChallengeRequest, opts ...grpc.CallOption) (*StartChallengeResponse, error)
	SubmitChallenge(ctx context.Context, in *SubmitChallengeRequest, opts ...grpc.CallOption) (*SubmitChallengeResponse, error)
	ResetChallenge(ctx context.Context, in *ResetChallengeRequest, opts ...grpc.CallOption) (*ResetChallengeResponse, error)
	// Terminal (first PTYData.data = challenge_id)
	ExecInstance(ctx context.Context, opts ...grpc.CallOption) (Breakfix_ExecInstanceClient, error)
	// Agent
	GenerateChallenge(ctx context.Context, in *GenerateChallengeRequest, opts ...grpc.CallOption) (*GenerateChallengeResponse, error)
}

type breakfixClient struct {
	cc grpc.ClientConnInterface
}

func NewBreakfixClient(cc grpc.ClientConnInterface) BreakfixClient {
	return &breakfixClient{cc}
}

func (c *breakfixClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breakfixClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breakfixClient) ListChallenges(ctx context.Context, in *ListChallengesRequest, opts ...grpc.CallOption) (*ListChallengesResponse, error) {
	out := new(ListChallengesResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/ListChallenges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breakfixClient) StartChallenge(ctx context.Context, in *StartChallengeRequest, opts ...grpc.CallOption) (*StartChallengeResponse, error) {
	out := new(StartChallengeResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/StartChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breakfixClient) SubmitChallenge(ctx context.Context, in *SubmitChallengeRequest, opts ...grpc.CallOption) (*SubmitChallengeResponse, error) {
	out := new(SubmitChallengeResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/SubmitChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breakfixClient) ResetChallenge(ctx context.Context, in *ResetChallengeRequest, opts ...grpc.CallOption) (*ResetChallengeResponse, error) {
	out := new(ResetChallengeResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/ResetChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breakfixClient) ExecInstance(ctx context.Context, opts ...grpc.CallOption) (Breakfix_ExecInstanceClient, error) {
	stream, err := c.cc.NewStream(ctx, &Breakfix_ServiceDesc.Streams[0], "/breakfix.Breakfix/ExecInstance", opts...)
	if err != nil {
		return nil, err
	}
	x := &breakfixExecInstanceClient{stream}
	return x, nil
}

type Breakfix_ExecInstanceClient interface {
	Send(*PTYData) error
	Recv() (*PTYData, error)
	grpc.ClientStream
}

type breakfixExecInstanceClient struct {
	grpc.ClientStream
}

func (x *breakfixExecInstanceClient) Send(m *PTYData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *breakfixExecInstanceClient) Recv() (*PTYData, error) {
	m := new(PTYData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *breakfixClient) GenerateChallenge(ctx context.Context, in *GenerateChallengeRequest, opts ...grpc.CallOption) (*GenerateChallengeResponse, error) {
	out := new(GenerateChallengeResponse)
	err := c.cc.Invoke(ctx, "/breakfix.Breakfix/GenerateChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BreakfixServer is the server API for Breakfix service.
// All implementations must embed UnimplementedBreakfixServer
// for forward compatibility
type BreakfixServer interface {
	// Auth
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Challenges
	ListChallenges(context.Context, *ListChallengesRequest) (*ListChallengesResponse, error)
	// Instance lifecycle (keyed by user + challenge_id)
	StartChallenge(context.Context, *StartChallengeRequest) (*StartChallengeResponse, error)
	SubmitChallenge(context.Context, *SubmitChallengeRequest) (*SubmitChallengeResponse, error)
	ResetChallenge(context.Context, *ResetChallengeRequest) (*ResetChallengeResponse, error)
	// Terminal (first PTYData.data = challenge_id)
	ExecInstance(Breakfix_ExecInstanceServer) error
	// Agent
	GenerateChallenge(context.Context, *GenerateChallengeRequest) (*GenerateChallengeResponse, error)
	mustEmbedUnimplementedBreakfixServer()
}

// UnimplementedBreakfixServer must be embedded to have forward compatible implementations.
type UnimplementedBreakfixServer struct {
}

func (UnimplementedBreakfixServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedBreakfixServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedBreakfixServer) ListChallenges(context.Context, *ListChallengesRequest) (*ListChallengesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChallenges not implemented")
}
func (UnimplementedBreakfixServer) StartChallenge(context.Context, *StartChallengeRequest) (*StartChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartChallenge not implemented")
}
func (UnimplementedBreakfixServer) SubmitChallenge(context.Context, *SubmitChallengeRequest) (*SubmitChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitChallenge not implemented")
}
func (UnimplementedBreakfixServer) ResetChallenge(context.Context, *ResetChallengeRequest) (*ResetChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetChallenge not implemented")
}
func (UnimplementedBreakfixServer) ExecInstance(Breakfix_ExecInstanceServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecInstance not implemented")
}
func (UnimplementedBreakfixServer) GenerateChallenge(context.Context, *GenerateChallengeRequest) (*GenerateChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateChallenge not implemented")
}
func (UnimplementedBreakfixServer) mustEmbedUnimplementedBreakfixServer() {}

// UnsafeBreakfixServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BreakfixServer will
// result in compilation errors.
type UnsafeBreakfixServer interface {
	mustEmbedUnimplementedBreakfixServer()
}

func RegisterBreakfixServer(s grpc.ServiceRegistrar, srv BreakfixServer) {
	s.RegisterService(&Breakfix_ServiceDesc, srv)
}

func _Breakfix_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breakfix_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breakfix_ListChallenges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChallengesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).ListChallenges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/ListChallenges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).ListChallenges(ctx, req.(*ListChallengesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breakfix_StartChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).StartChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/StartChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).StartChallenge(ctx, req.(*StartChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breakfix_SubmitChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).SubmitChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/SubmitChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).SubmitChallenge(ctx, req.(*SubmitChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breakfix_ResetChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).ResetChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/ResetChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).ResetChallenge(ctx, req.(*ResetChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Breakfix_ExecInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BreakfixServer).ExecInstance(&breakfixExecInstanceServer{stream})
}

type Breakfix_ExecInstanceServer interface {
	Send(*PTYData) error
	Recv() (*PTYData, error)
	grpc.ServerStream
}

type breakfixExecInstanceServer struct {
	grpc.ServerStream
}

func (x *breakfixExecInstanceServer) Send(m *PTYData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *breakfixExecInstanceServer) Recv() (*PTYData, error) {
	m := new(PTYData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Breakfix_GenerateChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakfixServer).GenerateChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breakfix.Breakfix/GenerateChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakfixServer).GenerateChallenge(ctx, req.(*GenerateChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Breakfix_ServiceDesc is the grpc.ServiceDesc for Breakfix service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Breakfix_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "breakfix.Breakfix",
	HandlerType: (*BreakfixServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Breakfix_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Breakfix_Login_Handler,
		},
		{
			MethodName: "ListChallenges",
			Handler:    _Breakfix_ListChallenges_Handler,
		},
		{
			MethodName: "StartChallenge",
			Handler:    _Breakfix_StartChallenge_Handler,
		},
		{
			MethodName: "SubmitChallenge",
			Handler:    _Breakfix_SubmitChallenge_Handler,
		},
		{
			MethodName: "ResetChallenge",
			Handler:    _Breakfix_ResetChallenge_Handler,
		},
		{
			MethodName: "GenerateChallenge",
			Handler:    _Breakfix_GenerateChallenge_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecInstance",
			Handler:       _Breakfix_ExecInstance_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "breakfix.proto",
}
